### ISSUE TITLE
0.44旋转木马不能使用

### ISSUE THREAD

**Issue by search-inner** [rilyu/teaset#10]
滑动一下就停不下来了一直滚动

**Comment by rilyu** [comment]
经测试在 RN 0.44 下运行良好，不管是模拟器还是手机上，请贴出你的代码，还有告知运行环境：iOS/Android，模拟器类型/真机型号

**Comment by search-inner** [comment]
测试过程中发现与其他组件冲突，与本插件无关，是我的问题，麻烦了

**Comment by search-inner** [comment]
测试旋转木马过程中发现正序轮播走一遍就停止不动了，而反向可以一直滚动，请问怎么解决
<Carousel
               style={styles.carousel}
               carousel={true}
               direction="backward"
               control={
                  <Carousel.Control
                    style={{alignItems: 'center'}}
                    dot={<Text style={styles.dot}>&bull;</Text>}
                    activeDot={<Text style={styles.activeDot}>&bull;</Text>}
                  />
                }
            >
                <Image  style={styles.itemImage}  source={{uri:'banner1'}} />
                <Image  style={styles.itemImage}  source={{uri:'banner2'}} />
                <Image  style={styles.itemImage}  source={{uri:'banner3'}} />
                <Image  style={styles.itemImage}  source={{uri:'banner4'}} />
                <Image  style={styles.itemImage}  source={{uri:'banner5'}} />
            </Carousel>

**Comment by rilyu** [comment]
经测试未发现此问题，请在独立的页面上单独测试以上Carousel组件代码，避免其它代码影响
