### ISSUE TITLE
Overlay中的 input 在 android 下无法输入字符

### ISSUE THREAD

**Issue by wr6412305** [rilyu/teaset#102]
Overlay.PopView Overlay.PullView 均有这个问题
Overlay中的 input 在 android 下无法输入字符,输入就自动删除

**Comment by rilyu** [comment]
你应该使用了 value 属性，由于 Overlay 组件不是调用者的子组件，因此无法监听调用者的状态变化，简单点，你可以使用 defaultValue 并监听 onChange 事件，或者按常规单独封装一个 Overlay 内部内容组件，在该组件内维护 value 状态。
