### ISSUE TITLE
PullPicker支持这种数据吗能否动态改变

### ISSUE THREAD

**Issue by PeterLocas** [rilyu/teaset#104]
"data": [
    {
      "id": "72577f84-952b-4228-aae5-770c688f049b",
      "name": "1",
      "sort": null
    },
    {
      "id": "4b981eb0-a644-4405-b75c-59950d0df1af",
      "name": "2",
      "sort": null
    }
  ]

**Comment by rilyu** [comment]
支持的，items 支持任何数组，每一项一个 item ，但需要在 getItemText 返回每一项的显示字符串或者 element

**Comment by mengerzhuanyong** [comment]
怎么使用啊
