### ISSUE TITLE
请问一下有底部的工具栏组件吗

### ISSUE THREAD

**Issue by giantss** [rilyu/teaset#107]
请问一下有底部的工具栏组件吗？
类似这样悬浮在底部的工具栏如何实现呢
![image](https://user-images.githubusercontent.com/13778798/33538335-b4dabd5e-d8fb-11e7-8fcf-d5a74210f12c.png)

**Comment by rilyu** [comment]
直接使用绝对定位就可以实现，需要解决的是键盘遮挡问题，https://github.com/rilyu/teaset/blob/master/components/Badge/Badge.js 使用 https://github.com/rilyu/teaset/blob/master/components/KeyboardSpace/KeyboardSpace.js 解决

**Comment by giantss** [comment]
哦 谢谢
