### ISSUE TITLE
[Feature]城市选择器

### ISSUE THREAD

**Issue by kala888** [rilyu/teaset#108]
是否可以提供城市选择器？
![image](https://user-images.githubusercontent.com/1215976/33555666-2699ce86-d93c-11e7-88ac-05b6512bdbb4.png)

**Comment by kala888** [comment]
Wheel 和 Drawer可以联合实现，是否可以考虑加到demo里面？

**Comment by rilyu** [comment]
Teaset 提供的都是很通用的组件，针对国内的城市选择这种定制化的组件暂不考虑提供，抱歉

**Comment by kala888** [comment]
@rilyu 放到demo里面吧，感觉挺常用的，我写了一个。仅供其他人参考，


import React from 'react'
import _ from 'lodash'
import { View, Button, Text, Left, Right } from 'native-base'

import { Wheel, Theme } from 'teaset'

import AREA from './area.json'

export default class CityPickerView extends React.PureComponent {
  constructor(props) {
    super(props)
    const { province = '北京', city = '北京' } = this.props

    const pi = _.findIndex(AREA, item => {
      item.name === province
    })
    const provinceIndex = pi === -1 ? 0 : pi
    const provinceData = AREA.map(item => item.name)

    const cityIndex = _.findIndex(AREA, item => {
      item.name === city
    })

    const cityData = AREA[provinceIndex].city.map(item => item.name)

    this.state = {
      provinceData,
      provinceIndex,
      cityData,
      cityIndex: cityIndex === -1 ? 0 : cityIndex,
    }
  }

  onAreaChange = provinceIndex => {
    if (provinceIndex !== this.state.provinceIndex) {
      this.setState({
        provinceIndex,
        cityData: AREA[provinceIndex].city.map(item => item.name),
        cityIndex: 0,
      })
    }
  }

  onCityChange = cityIndex => {
    this.setState({
      cityIndex,
    })
  }

  onSubmit = () => {
    const province = this.state.provinceData[this.state.provinceIndex]
    const city = this.state.cityData[this.state.cityIndex]
    const result = province === city ? city : `${province} ${city}`
    this.props.callback && this.props.callback(result)
    this.close()
  }
  close = () => {
    this.props.close && this.props.close()
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ flexDirection: 'row', justifyContent: 'center' }}>
          <Left>
            <Button onPress={this.close} small transparent bordered>
              <Text>取消</Text>
            </Button>
          </Left>
          <View>
            <Button disabled transparent>
              <Text>请选择</Text>
            </Button>
          </View>
          <Right>
            <Button onPress={this.onSubmit} small transparent bordered>
              <Text>确定</Text>
            </Button>
          </Right>
        </View>
        <View
          style={{
            backgroundColor: Theme.defaultColor,
            padding: 20,
            flexDirection: 'row',
            justifyContent: 'center',
          }}
        >
          <Wheel
            style={{ height: 150, width: 120 }}
            itemStyle={{ textAlign: 'center' }}
            items={this.state.provinceData}
            index={this.state.provinceIndex}
            onChange={index => this.onAreaChange(index)}
          />
          <Wheel
            style={{ height: 150, width: 120 }}
            itemStyle={{ textAlign: 'center' }}
            items={this.state.cityData}
            index={this.state.cityIndex}
            onChange={index => this.onCityChange(index)}
          />
        </View>
      </View>
    )
  }
}



import React from 'react'
import { View } from 'native-base'
import { Drawer, Theme } from 'teaset'

import CityPickerView from './CityPickerView'

export default class CityPicker extends React.PureComponent {
  static drawer
  static open = (callback, province, city) => {
    const viewer = (
      <View style={{ backgroundColor: Theme.defaultColor, height: 260 }}>
        <View
          style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
        >
          <CityPickerView
            province={province}
            city={city}
            close={CityPicker.close}
            callback={callback}
          />
        </View>
      </View>
    )
    this.drawer = Drawer.open(viewer, 'bottom')
  }
  static close = () => {
    this.drawer && this.drawer.close()
  }
}

**Comment by limintao** [comment]
@kala888 你写的城市选择器有demo演示和代码地址吗？

**Comment by oMhuAaN** [comment]
我也自己写了一个地区选择器，但是选了省，市和区无法自动更新，设置state了也无变化，可能会是什么原因呢

**Comment by oMhuAaN** [comment]
刚刚状态改变，但是没有重新渲染是因为都杂糅到同一个组件里面，太混乱了，现在把它分开成两个组件，问题解决了，
