### ISSUE TITLE
ModalIndicator自定义图标

### ISSUE THREAD

**Issue by huncent** [rilyu/teaset#11]
可以自定义那个loading的图标吗？我做一个录音的场景录音时想用这个实现累次微信录语音的效果

**Comment by rilyu** [comment]
ModalIndicator 设计的目的是用于页面加载动画提示，你这个目的并不一样，可以仿照ModalIndicator 自己写一个，动画实现建议使用 airbnb 开源的 lottie-react-native

**Comment by huncent** [comment]
谢谢答复，很好的建议，我会尝试一下的
