### ISSUE TITLE
<SegmentedView /> 分段器   问题

### ISSUE THREAD

**Issue by zhangyanlf** [rilyu/teaset#110]
![04dc548b0d94de89a2b87417c5502f3e](https://user-images.githubusercontent.com/22088934/33591794-89c7ae02-d9c2-11e7-89d0-1d1ad6846b17.jpg)
![57a421395a76e45e1e5cf71ce631832b](https://user-images.githubusercontent.com/22088934/33591797-8e7c44e4-d9c2-11e7-9b08-3d4329a55bdd.jpg)

分段器中不能修改title字体的大小，这两种方法都不行，改默认的字体大小也没有变化。

**Comment by rilyu** [comment]
不确定你这段代码的用途，你打开 example 中的 SegmentedViewExample.js，第 61 行修改为
```javascript
        <Label style={{color: tintColor, paddingTop: 4}} text={titles[index]} size='xl' />
```
然后运行例子，在 SegmentedViewExample 页面打开 custom 开关就能看到效果了，你可以传入任何组件

**Comment by zhangyanlf** [comment]
谢谢了，已经解决，忽略了一个属性
