### ISSUE TITLE
Menu shadow属性无效啊

### ISSUE THREAD

**Issue by giantss** [rilyu/teaset#112]
ios上
![image](https://user-images.githubusercontent.com/13778798/33595436-1e8433fc-d9d3-11e7-97ce-4ed42b3d2e9d.png)

**Comment by rilyu** [comment]
有效的，只是黑色的菜单背景和黑色的阴影对比不明显

**Comment by giantss** [comment]
这种效果可以设置吗？就是弹出菜单时全屏背景变暗或者模糊
![img_2853](https://user-images.githubusercontent.com/13778798/33701228-de1065f2-db58-11e7-8acd-da84a66527be.PNG)

**Comment by rilyu** [comment]
传入 overlayOpacity: 0.4 或其它值就可以了
不过截图这个不是 Menu ，应该使用 Overlay 或 Drawer 来实现

**Comment by giantss** [comment]
嗯，谢谢 我知道 只是一个展示图
