### ISSUE TITLE
关于Toast组件

### ISSUE THREAD

**Issue by puti94** [rilyu/teaset#113]
1.有个提议，如果连续多次Toast.show()会视图会叠加，建议Toast.show之前先调用一次Toast.hide(key)，
这样会不会更好点？
2.有没有办法直接改变Toast背景色，我要是设置contentStyle: {backgroundColor: 'red'}则会替换掉项目中的设置。要不只能修改源代码了

**Comment by rilyu** [comment]
1、有考虑过，但显示前隐藏上一个并不是太好的方式，可能会导致信息一闪而过甚至不显示而导致信息无法到达用户，目前解决这个问题一般采用两种方法，一是在屏幕上部用先进先出的列表显示，每一个 timeout 后自行消失；二是使用消息列表延迟显示，在上一个消失后再显示下一个消息，这两种方法都不太好，所以暂时保留了最原始的方式；
2、可以这么统一修改，只需要在App初始化是执行一次
```javascript
Theme.set({toastColor: 'red'});
```
其它配置可参考ThemeDefault.js

**Comment by puti94** [comment]
@rilyu 了解，谢谢了，对于第一点，那我就代码自己改了，因为我个人习惯只显示一个，以及会在写代码的时候考虑显示不全的情况
