### ISSUE TITLE
能添加typescript支持么

### ISSUE THREAD

**Issue by yuwenhuisama** [rilyu/teaset#114]
没有相应的头文件，用着比较麻烦。

**Comment by rilyu** [comment]
我没在使用 typescript ，抱歉

**Comment by qq326646683** [comment]
有空支持一下吗 @rilyu ，公司在用typescript，很无奈用不了，又不会写d.ts

**Comment by fantasy525** [comment]
同求支持typescritp啊，希望支持一下写个声明文件吧大佬
