### ISSUE TITLE
npm,yarn都装不了，装到一半都直接结束了

### ISSUE THREAD

**Issue by HaoXioong** [rilyu/teaset#115]
PS H:\Beverley> npm install teaset --save
PS H:\Beverley> yarn add teaset --save
yarn add v1.3.2
[1/4] Resolving packages...
⠈ react-native-deprecated-custom-components@github:facebookarchive/react-native-custom-components
PS H:\Beverley>

**Comment by rilyu** [comment]
我试了一下npm可以成功安装，如果你的网络访问npm不太稳定，建议使用taobao的npm镜像：http://npm.taobao.org
