### ISSUE TITLE
wheel组件和select组件能和在一起用么，点击选择框底部弹出wheel

### ISSUE THREAD

**Issue by HaoXioong** [rilyu/teaset#119]
wheel组件和select组件能和在一起用么，点击选择框底部弹出wheel

**Comment by HaoXioong** [comment]
顺便问一下为甚么listrow组件的分割线粗细不一样呢

**Comment by rilyu** [comment]
Select 组件很简单，如需要使用 wheel 可参考源代码自定义一个组件
ListRow 分隔线是一样的，模拟器会有缩放变形，真机运行就没问题
