### ISSUE TITLE
Carousel组件点击事件

### ISSUE THREAD

**Issue by giantss** [rilyu/teaset#121]
`Carousel`组件没有点击事件吗？是不是需要自己在`Image`组件外面套一层类似`TouchableHighlight`的组件然后实现点击事件呢

**Comment by rilyu** [comment]
Carousel 跟很多 react native 组件一样是没有点击事件的，可以按你自己的习惯增加 Touchable 类组件支持

**Comment by giantss** [comment]
好的，谢谢
