### ISSUE TITLE
Select右侧Icon怎么替换

### ISSUE THREAD

**Issue by pingxiaodou** [rilyu/teaset#123]
Select框右侧Icon是否可以自定义?在文档中没有找到相关属性

**Comment by kala888** [comment]
不改源码不能换的，代码里写死了，可以稍微绕过去，就是设置iconTintColor="transparent"，然后把你自己的icon放到select后面，不过要注意处理一下那个icon的点击事件

https://github.com/rilyu/teaset/issues/126
