### ISSUE TITLE
Toast 组件 center 不居中问题

### ISSUE THREAD

**Issue by ldhios** [rilyu/teaset#127]
当设置 Toast 消息显示的位置为center的时候 . 在ios 的手机上. 显示是减掉了 navgationBar的高度后的居中, 而不是算整个屏幕的高度.  在 iphone x上有navgationBar的高度比以前更高. 显示很不协调

**Comment by rilyu** [comment]
可以通过设置 toastScreenPaddingTop 和 toastScreenPaddingBottom 的值来调整对齐位置，默认值：
```javascript
  toastScreenPaddingTop: 100,
  toastScreenPaddingBottom: 80,
```
设置方法：
```javascript
Theme.set({toastScreenPaddingTop: 80});
```
