### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by xuechinahb** [rilyu/teaset#129]
适配iPhone X，有bug。
teaset版本：0.5.0，0.5.1。
使用iPhone X测试。在react-native@0.50.4上正常。在react-native@0.44.3出错，D_HEIGHT找不到。r然后看了themes/Theme.js的代码，D_HEIGHT和D_WIDTH 确实没有定义，只好手动改了...

**Comment by rilyu** [comment]
谢谢，稍等我改一下
