### ISSUE TITLE
TabView 点击tabbar重新更新数据

### ISSUE THREAD

**Issue by zust-hh** [rilyu/teaset#130]
TabView 中页面只加载一次，我想在点击某一个tabbar后重新更新数据，怎么实现？

**Comment by rilyu** [comment]
在 TabView.onChange 事件中调用 index 对应的页面的 forceUpdate 方法

**Comment by zust-hh** [comment]
具体怎么操作？有点不太明白`<TabView onChange={index => index == 0 && this.refs.home && this.refs.home.fetchData()}>
  <TabView.Sheet>
    < HomePage ref='home' />
  </TabView.Sheet>
</TabView>`

**Comment by zust-hh** [comment]
![image](https://user-images.githubusercontent.com/26922852/34205287-cfcd7552-e5bc-11e7-8b77-82652a7eb5a3.png)
我的代码是这样，能稍微写个事例吗，我想点击那个发现，刷新发现页面的数据
