### ISSUE TITLE
NavigationPage相关

### ISSUE THREAD

**Issue by aoldcat** [rilyu/teaset#131]
请问使用使用NavigationPage如何进行页面传值,在this.navigator.push({ view:<PageParams/>) ,如何传递参数给下个页面呢以及参数回调呢.

**Comment by rilyu** [comment]
使用下个页面的属性，例：
```javascript
this.navigator.push({view: <Example title='测试' onSubmit={data => {
  alert(data);
}} />})
```
在 Example 中调用 this.props.onSubmit 回调即可

**Comment by aoldcat** [comment]
嗯,回调是正常的,传递参数给下个页面接受是如何呢.谢谢.

**Comment by aoldcat** [comment]
好了,谢谢,很棒的项目.
