### ISSUE TITLE
Toast custom 加载提示框能否做一个mark，弹出的时候页面的其他部分不可点击

### ISSUE THREAD

**Issue by Mscynol** [rilyu/teaset#132]
现在弹出这个Toast，页面任何按钮都还能够点击

**Comment by rilyu** [comment]
```javascript
Toast.show({
  text: 'Modal toast',
  duration: 2000,
  position: 'center',
  overlayPointerEvents: 'auto',
  modal: true,
  overlayOpacity: 0.4
});
```
可以查看一下组件继承树，有很多属性可以定制的

**Comment by Mscynol** [comment]
嗯嗯 突然发现太赞啦，目前咱们有没有类似对话框的这种

**Comment by rilyu** [comment]
使用 Overlay.PopView 很容易实现对话框，具体参考 OverlayExample.js

**Comment by Mscynol** [comment]
static show = (title,message, buttons) => {
		let overlayView = (
			<Overlay.PopView
				style={{alignItems: 'center', justifyContent: 'space-around'}}
				type={'zoomIn'}
				modal={false}
				ref={v => this.overlayPopView = v}
			>
				<View style={{
					backgroundColor: Theme.defaultColor,
					minWidth: 260,
					minHeight: 160,
					borderRadius: 12,
					justifyContent: 'center',
					alignItems: 'center'
				}}>
					<Text style={{fontWeight: 'bold', fontSize: 18,}}>{title}</Text>
					<Text style={{fontSize: 16,marginTop:20}}>{message}</Text>
					<View style={{
						flexDirection: 'row',
						height:40,
						alignItems:'center',
						justifyContent: 'space-around',
					}}>
						{buttons.map((title, i) => {
							return (
								<TouchableOpacity
									key={i}
									style={{backgroundColor:'red',
									
									}}
									onPress={title.onPress}
									activeOpacity={0.6}
								>
									<Text style={{alignSelf:"center"}}>{title.title}</Text>
								</TouchableOpacity>);
						})}
					</View>
				</View>
			</Overlay.PopView>
		);
		Overlay.show(overlayView);
	}
onpress 怎么把当前实例overlayview 传进去啊，让点击回调的时候关掉对话框

**Comment by Mscynol** [comment]
按钮的位置我现在也不知道怎么去控制在底部，随着button一个撑满底部，两个平分
