### ISSUE TITLE
请问Menu组件中，每一栏目的分割线可以设置成和文字对齐而不是一整行吗？

### ISSUE THREAD

**Issue by danna88** [rilyu/teaset#134]
如题，是不是要改源码才行呢？

**Comment by rilyu** [comment]
设置 Theme 把分隔线高度设置为 0，然后自己渲染 item 并渲染分隔线
Menu 组件很简单，建议你参照源代码来封装一个，而不是直接修改源代码

**Comment by danna88** [comment]
嗯呢，明白了，谢谢。
