### ISSUE TITLE
Can't find variable: process

### ISSUE THREAD

**Issue by jackqqxu** [rilyu/teaset#136]
Can't find variable: process (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:12)

Can't find variable: process (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:12)

http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:12:232
o@http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:2:1408
http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:2:678
t@http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:2:755
global code@http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=true:13:9

**Comment by rilyu** [comment]
teaset 代码中没有用到 process 变量，请检查其它代码

**Comment by internet5** [comment]
下载本项目，在example里安装运行，我也出现里这个问题啊，没有其他东西啊，怎么回事
