### ISSUE TITLE
请问如何让导航栏用图片做背景

### ISSUE THREAD

**Issue by StarOfLife** [rilyu/teaset#137]
请问该怎么实现用图片做导航条的背景呢。采用ImageBackground 包裹NavigationBar的方式没有成功

**Comment by rilyu** [comment]
已增加 NavigationBar.background 属性，请参考文档及 example
https://github.com/rilyu/teaset/commit/64f7994addc86e34a7ae1b50ccc007d5093996d3

**Comment by StarOfLife** [comment]
@rilyu 多谢大佬了(*^__^*)
