### ISSUE TITLE
Select显示BUG

### ISSUE THREAD

**Issue by pingxiaodou** [rilyu/teaset#139]
react-native版本: 0.46.4
teaset版本: 0.5.2

`代码如下:<ListRow title={
                    <View style={{flexDirection: 'row'}}>
                        <Text style={{color: '#333333', fontSize: 13}}>牌照类型:</Text>
                    </View>
                }
                         activeOpacity={0.8}
                         detail={
                             <Select
                                 style={{flex: 1}}
                                 size='sm'
                                 pickerType={"popover"}
                                 value={this.state.licensePlateType}
                                 items={this.state.licensePlateTypeList}
                                 placeholder='请选择牌照类型'
                                 pickerTitle='牌照类型'
                                 icon={<Icon name={'ios-arrow-forward'} style={{fontSize: 15, color: colors.placeHolderColor}}/>}
                                 valueStyle={{textAlign: 'right'}}
                                 getItemValue={(item, index) => item.code}
                                 getItemText={(item, index) => item.name}
                                 onSelected={(item, index) => this.setState({
                                     licensePlateType: item.code,
                                 })}
                             />
                         }
                />`
显示效果如下:
![image](https://user-images.githubusercontent.com/23648004/34343994-bb335d3e-ea1a-11e7-9b86-2b3e37577ccc.png)

请问是什么原因造成的?

**Comment by rilyu** [comment]
我测试了一下在 iOS 和 Android 下均没发现上述问题，目前 teaset 开发使用的 react-native 版本是 0.50 或以上，不确定在旧版本是否会出现问题，精力有限也无法把各版本都测试一遍，建议使用 teaset 历史版本试试，比如 0.2.6 ，功能会有所减少

**Comment by pingxiaodou** [comment]
好的,多谢回复
