### ISSUE TITLE
import {Carousel} from 'teaset'时会改变 默认的背景颜色?(改成了深黑色)

### ISSUE THREAD

**Issue by LDty** [rilyu/teaset#141]
import React from 'react';
import { ScrollView, View, Text, StyleSheet, Animated, Image } from 'react-native';
import { StackNavigator } from 'react-navigation'; // 1.0.0-beta.14
import {Carousel} from 'teaset';
只import了这些

**Comment by rilyu** [comment]
是的，你可以使用 Theme.set({screenColor: '#fff'}) 修改
或者在代码的最外层 View 设置一个背景色，这种方式更为合适

**Comment by LDty** [comment]
恩 好的 谢谢

**Comment by supermanxiacheng** [comment]
偷偷告诉你,可以去Theme.default 找screenColor 改 - -
不过现在改这个没什么太大意义了,因为你总要包一层safeAreaView的...
很少有机会看到teaset的默认颜色了
