### ISSUE TITLE
Generating the release APK, png  parsing problem

### ISSUE THREAD

**Issue by supermanxiacheng** [rilyu/teaset#142]
android/app/build/intermediates/res/merged/release/drawable-xxhdpi-v4/node_modules_teaset_icons_success.png: 
error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

![pic](https://ws2.sinaimg.cn/large/006tNc79gy1fmvclaegfpj31kw0cxq3j.jpg)

这个问题是个例,还是有问题...不知道怎么解决

**Comment by rilyu** [comment]
应该跟你的打包工具有关，上网自行搜索一下解决办法吧

**Comment by supermanxiacheng** [comment]
谢谢,果然和打包工具有关. 
而且,算是最近出的共性问题.在react-navigation,也有一个issue,讨论png 报错.
https://github.com/react-community/react-navigation/issues/1976
解决方法是
for now in your top-level gradle.properties file add this line: android.enableAapt2=false which essentially uses the old aapt for resources.
