### ISSUE TITLE
apk安装成功后运行闪退

### ISSUE THREAD

**Issue by theNinthDay** [rilyu/teaset#145]
是这样的，我用的是最新的0.51的react native，直接按照官方的文档签名打包的apk（realese），然后下面分几种情况描述下：
1.用react-native生成的源码打出来的apk，在真机上安装运行，可以正常运行
2.引入teaset，但是不在界面引入组件，打apk，在真机上安装运行，也可以正常运行
3.引入teaset，在界面使用了导航栏和底部栏，电脑接真机调试，也可以正常运行
4.3的情况，打apk，发现在真机上安装成功后，运行却是闪退
5.于是我去把teaset的example也签名打包了，装真机上也是闪退（同样：模拟器调试、真机调试都是可以正常的）

按照rn官方文档签名打包的，且可以正常安装，这个步骤应该是没有问题的
刚刚接触移动端开发，不知道如何解决，求老司机帮助
环境：react native v0.51.0
          teaset 0.5.3
          运行手机：魅族pro7 plus
          系统： Flyme6.1.2.5A  （Android 7.0）
          编译打包环境： MacOS 10.13.2  

下面是我adb logcat查到的一个导致崩溃的异常，但是不知道为何

> 12-28 13:12:33.202 17768 17789 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
12-28 13:12:33.202 17768 17789 E AndroidRuntime: Process: com.yonthfuzhou, PID: 17768
12-28 13:12:33.202 17768 17789 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 
12-28 13:12:33.202 17768 17789 E AndroidRuntime: This error is located at:
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in Navigator
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in RCTView
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in t
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in t
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in RCTView
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in n
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in RCTView
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in t
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in n
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in RCTView
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in RCTView
12-28 13:12:33.202 17768 17789 E AndroidRuntime:     in t, stack:
12-28 13:12:33.202 17768 17789 E AndroidRuntime: componentWillUnmount@399:183
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@151:2908
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@151:2884
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@41:26461
12-28 13:12:33.202 17768 17789 E AndroidRuntime: mountClassInstance@41:26516
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@41:30490
12-28 13:12:33.202 17768 17789 E AndroidRuntime: beginWork@41:30525
12-28 13:12:33.202 17768 17789 E AndroidRuntime: q@41:47219
12-28 13:12:33.202 17768 17789 E AndroidRuntime: ee@41:47820
12-28 13:12:33.202 17768 17789 E AndroidRuntime: ne@41:48894
12-28 13:12:33.202 17768 17789 E AndroidRuntime: ue@41:51348
12-28 13:12:33.202 17768 17789 E AndroidRuntime: ae@41:50649
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@41:57228
12-28 13:12:33.202 17768 17789 E AndroidRuntime: updateContainer@41:57235
12-28 13:12:33.202 17768 17789 E AndroidRuntime: render@41:79022
12-28 13:12:33.202 17768 17789 E AndroidRuntime: exports@277:171
12-28 13:12:33.202 17768 17789 E AndroidRuntime: run@273:601
12-28 13:12:33.202 17768 17789 E AndroidRuntime: runApplication@273:2032
12-28 13:12:33.202 17768 17789 E AndroidRuntime: value@18:3177
12-28 13:12:33.202 17768 17789 E AndroidRuntime: <unknown>@18:911
12-28 13:12:33.202 17768 17789 E AndroidRuntime: value@18:2606
12-28 13:12:33.202 17768 17789 E AndroidRuntime: value@18:883
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
12-28 13:12:33.202 17768 17789 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
12-28 13:12:33.203  1089  2241 I ActivityManager: addErrorToDropBox com.yonthfuzhou crash

**Comment by auven** [comment]
我昨天也遇到了一样的问题，这个是因为 react native 依赖的某个第三方库升级导致的，你可以参考这个来处理：https://github.com/facebook/react-native/issues/17348 。

解决方法是：npm install uglify-es@3.2.2 --save ，将 uglify-es 这个包会退到 3.2.2 版本

**Comment by chenweigh** [comment]
我新 init 出来的一个工程，然后，执行react-native bundle --platform android --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --dev false --reset-cache --assets-dest android/app/src/main/res/。之后运行 react-native run-android.出现'this._subscribablesubsciptions.forEach'这种错误。
------
然后我尝试了npm install uglify-es@3.2.2 --save，也还是上述错误。

**Comment by chenweigh** [comment]
好使了，npm install 之后，package.json,添上
"resolutions": {
    "uglify-es": "3.2.2"
  }
 之后，
react-native bundle --platform android --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --dev false --reset-cache --assets-dest android/app/src/main/res/
在，react-native run-android。
成功了🙂

**Comment by theNinthDay** [comment]
npm install uglify-es@3.2.2 --save
完美解决

但是按他们说的只加
"resolutions": {
"uglify-es": "3.2.2"
}
反而不行

不管怎样，感谢了
