### ISSUE TITLE
TabView icon过大android显示不全

### ISSUE THREAD

**Issue by Jinran** [rilyu/teaset#149]
TabView.sheet ico设置 超过44宽度的图标时，android环境下会显示不全图标，被 TabButton组件限制，
<img width="449" alt="wx20171229-111829 2x" src="https://user-images.githubusercontent.com/16407903/34428676-5a01838e-ec8a-11e7-9119-8cc774b7c340.png">

在TabView.js中 buttonStyle添加 flex或指定width可修改正常，是否可以添加到下一个版本中去允许自定义修改TabButton样式，或自适应TabButton
<img width="344" alt="wx20171229-112311 2x" src="https://user-images.githubusercontent.com/16407903/34428810-6198249e-ec8b-11e7-9407-383d0c99ce84.png">
<img width="340" alt="wx20171229-112329 2x" src="https://user-images.githubusercontent.com/16407903/34428827-85519956-ec8b-11e7-8a7d-e8f5520655e8.png">
#

**Comment by rilyu** [comment]
你可以设置宽度的，Theme.set({tvBarBtnWidth:60})
至于为什么采用这种方式我不记得了，rn的组件在android下各种不一致，修改的话需要各种情况都测一遍，看是否很有必要再修改

**Comment by Jinran** [comment]
好的，我这就去试试，
那么如果修改 tabbar button 的 activeOpacity 值 如何来通过theme来修改呢，点击以后透明度高，后面的横线都能看见啦
