### ISSUE TITLE
还有新增组件的计划吗？

### ISSUE THREAD

**Issue by lihangyu89** [rilyu/teaset#15]
hi,大神
  还准备开发些新组件吗?比如DatePicker,抽屉组件,等等。。。

**Comment by rilyu** [comment]
后续会开发新组件的，但应该只会开发纯 JS 组件。
我有封装了一个 DatePicker 组件，分别使用 DatePickerIOS 和 DatePickerAndroid 来实现，这个组件在 iOS 和 Android 系统差异比较大，且 DatePickerIOS 有 bug 而 Facebook 一直不解决，所以没放进来。
抽屉组件其实已经有了，你运行 TeasetExample，在 Overlay 中点 Pull and translate，就是手机QQ效果的抽屉

**Comment by lihangyu89** [comment]
it's great !
