### ISSUE TITLE
Overlay.PopView与TransformView组合会出现问题

### ISSUE THREAD

**Issue by jiasongs** [rilyu/teaset#154]
![1bee0352-80f7-4ba4-9dfa-d3e3ee44bd8b](https://user-images.githubusercontent.com/22904757/34594729-d0b575ac-f20d-11e7-8c95-3f74cef2d0de.png)

![1f0bb629-59aa-47be-92d1-861ce9de1fdf](https://user-images.githubusercontent.com/22904757/34594669-6c1a8c4a-f20d-11e7-8e9c-1aa56690399a.png)

**Comment by rilyu** [comment]
一般情况下 PopView 使用于弹出框，需要制定宽和高，如果需要全屏，则要传入 containerStyle 确保容器占满全屏，可以用绝对定位或者 flex=1

**Comment by jiasongs** [comment]
非常感谢！Overlay.PopView与TransformView组合使用不能达到我的需求，类似微博，QQ，微信查看图片的方式（从指定位置放大到全屏），但是我发现使用<AlbumView /> + Overlay.PopView可以实现我的功能，不过我希望teaset出一个类似的控件。再次感谢作者的贡献！

**Comment by rilyu** [comment]
有了，AlbumView，参考 example
