### ISSUE TITLE
ActionSheet的子元素部分属性无法自定义

### ISSUE THREAD

**Issue by StarOfLife** [rilyu/teaset#155]
在使用ActionSheet的时候，遇到了四个问题，希望大大能够抽时间看下。
1、想改变ActionSheetView.Item分割线的颜色以及是否是full还是indent。好像并没有提供配置去修改。
2、点击item时候的activeOpacity也无法自定义。
3、如果设置containerStyle的背景色为白色之外的其他颜色，会发现每个选项之间除了分割线外，还有1物理像素的缝隙。
4、TouchableOpacity能否替换为TouchableHighlight。同时提供设置透明度，按下时候背景色的接口

**Comment by rilyu** [comment]
ActionSheet 是一个很简单的组件，近似于微信的简约风格，这种封装组件没有提供太多的属性，避免学习成本过高，如需更多的定制化样式，建议参照 ActionSheet 写一个，代码很简单的

**Comment by StarOfLife** [comment]
是我陷入了思维误区了。复制修改了份

**Comment by zi6xuan** [comment]
[根据源代码是支持自定义Title的，但是当我传入自定义view作为title的时候，会出现一个类型检查的警告，但是实际渲染又并没有出现问题
![image](https://user-images.githubusercontent.com/13834481/52771911-85c60000-307a-11e9-99bf-c939b3a0a70b.png)

**Comment by rilyu** [comment]
fixed: https://github.com/rilyu/teaset/commit/fc58311f61f36f45f866f8c2426401f03bf5fb1f
