### ISSUE TITLE
Overlay.PopView custom自定义位置Pop，但是返回时却回不到原来的位置。

### ISSUE THREAD

**Issue by jiasongs** [rilyu/teaset#156]
查看了一下源代码，从自定义的位置放大到全屏，这个是没有问题的。但是，从全屏缩小到自定义位置还是用的fromReact，理论上来说没有问题。实际上，回不到原来的位置，总是差一截。
![default](https://user-images.githubusercontent.com/22904757/34656163-c82a2bc2-f450-11e7-8ace-8e99619935dc.png)
这样的图片布局尤其明显。

**Comment by rilyu** [comment]
小图和全屏的横宽比是有差异的，并且全屏显示时还可能存在空白边框，经过换算后位置可能会不太准，使用 transform 只能做到这种效果了
