### ISSUE TITLE
NavigationBar的返回按钮颜色无法自定义

### ISSUE THREAD

**Issue by StarOfLife** [rilyu/teaset#158]
NavigationBackButton的文字颜色和返回图片颜色取的是this.context.tintColor。但是当我的NavigationBar颜色为白色时候，就无法显示出来。打印发现this.context.tintColor颜色为#fff

**Comment by rilyu** [comment]
在 NavigationBar 的 tintColor 属性传入左右按钮颜色，参考 NavigationBarExample

**Comment by StarOfLife** [comment]
可以了。谢谢
