### ISSUE TITLE
Button的disabled问题

### ISSUE THREAD

**Issue by misakichan** [rilyu/teaset#162]
teaset ^0.5.3
react 16
rn 0.51

1.设置Button A 和 Button B 的disable分别为 this.state.flag和 !this.state.flag.
2.设置初始state.flag = false;
3.A绑定方法里有 this.setState({flag: true});  B绑定方法里有this.setState({flag: false});

期望效果是：
初始状态A为高亮可点，B为阴影不可点；
点击A后，A为阴影不可点，B为高亮可点；
再点击B后，A为高亮可点，B为阴影不可点；

实际效果：
初始状态A为高亮可点，B为阴影不可点；（没毛病）
点击A后，A为高亮不可点，B为高亮可点；（是否可点没毛病，但是A的样式没刷新）
再点击B后，A为高亮可点，B为高亮不可点；（是否可点没毛病，但是B的样式没刷新）

**Comment by rilyu** [comment]
是有这个问题，TouchableOpacity 修改 opacity 不起作用，暂时没空修正这个 bug ，临时解决方案建议给 A 和 B 都加一个 key 属性，且保证 disable 值不一样时 key 属性值也不一样

**Comment by rilyu** [comment]
已修复 https://github.com/rilyu/teaset/commit/32edf3f04ad08eb0fe5f051452c667ea67446e67
