### ISSUE TITLE
分隔线的显示问题

### ISSUE THREAD

**Issue by pingxiaodou** [rilyu/teaset#164]
在ListRow组件和Select组件中分隔线的高度为1 / PixelRatio.get(), 在部分android中分割线显示不全(有些线能显示出来,有些线显示不出来),如下图:
![image](https://user-images.githubusercontent.com/23648004/35189763-f72db6e6-fe8c-11e7-95ee-164698e81af6.png)
![image](https://user-images.githubusercontent.com/23648004/35189764-ff7c2b2a-fe8c-11e7-8c00-027e74d38c73.png)
![image](https://user-images.githubusercontent.com/23648004/35189768-0a50cd30-fe8d-11e7-9b46-e6b306bbff25.png)

以上三图分别是小米5,一加3,小米MIX2的显示效果

**Comment by rilyu** [comment]
确认是在真机中出现这个问题么？ListRow 默认使用1像素（不是1px）的分隔线，如果在模拟器中可能会因为缩放原因导致显示不出来，测试过很多机器都可以正常工作，如在真机中也出现这个问题，建议修改 Theme.set({rowSeparatorLineWidth: 1}) 修改为1px以确保正常工作，此时分隔线会显得比较粗

**Comment by pingxiaodou** [comment]
是在真机上出现的问题,用过其他组件如Ant-designMobile也有类似问题,只好修改宽度解决了,Thanks

**Comment by zhenizhui** [comment]
的确，一加3T，Android 8.0.0 上有这个问题
![bug](https://user-images.githubusercontent.com/13503884/40238594-3a347190-5ae6-11e8-9048-25e96492def5.png)

```
// 即可解决
componentDidMount () {
  Theme.set({rowSeparatorLineWidth: 1})
}
```
