### ISSUE TITLE
关于导航器

### ISSUE THREAD

**Issue by wq13718048209** [rilyu/teaset#17]
0.44以后facebook推出了新的导航 来解决卡顿的问题  作者什么时候把新导航加进来啊 老的那个慢慢就废弃掉了

**Comment by rilyu** [comment]
暂时没有使用 react-navigation 的计划，差异太大了。
Teaset 中与页面导航相关的仅以下三个组件，并不影响其它组件。
```
<TeaNavigator />
<BasePage />
<NavigationPage />
```

**Comment by zengqingsong** [comment]
请问导航怎么传递参数。能否做一个案例。

**Comment by wq13718048209** [comment]
希望作者继续更新  加入更多好用的组件  会一如既往的支持

**Comment by zengqingsong** [comment]
是个好的项目，希望能够把做APP的一些重复的工作省下来，专注于业务逻辑。

**Comment by zengqingsong** [comment]
`   renderRow(item, sectionID, rowID, highlightRow) {
        //传递参数给详情页面
        // const {navigate} = this.props.navigator;
        let article = {
            url: item['detail_url'],
            title: item['title'],
            userName: item['title'],
            contentImg: item['cover_url']
        };
        // let article = {
        //     url: 'http://www.zengqs.com/index.php?s=/mobile/news/detail/id/35.html',
        //     title: '文章标题',
        //     userName: '青伢子',
        //     contentImg: 'http://www.zengqs.com/Uploads/Picture/Spider/33d15aa3fd659f5b9c034ca4db6e6715.jpg',
        // };
        // this.navigation.push({view: <WebPage />});

        const nextRoute = {
            view: <WebPage
                article={article}
            />,
        };
        return (
            <View style={styles.itemContainer}>
                <ImageButton
                    source={{uri: item.cover_url}}
                    style={{width: 120, height: 80,}}
                    onPress={() => this.navigator.push(nextRoute)}
                />
                <TouchableOpacity
                    onPress={() => this.navigator.push(nextRoute)}
                    style={styles.rightContainer}>
                    <Text numberOfLines={4} ellipsizeMode='tail'>
                        {item.title}
                    </Text>
                    <Text>{item.create_time}</Text>
                </TouchableOpacity>
            </View>
        );
    }`

**Comment by zengqingsong** [comment]
我觉得这种导航机制比官方的那种要简单好用，需要的时候注册就可以用，而不是在一开始全部注册。不知道我的理解对不对，弄React native才2天时间，正在学习做一个APP，以前用HBuilder搞的太慢了。

**Comment by wq13718048209** [comment]
是的  官方最新的那种确实需要一开始都注册  因为我就是这么写的

**Comment by zengqingsong** [comment]
我上午做的方案是全部注册，后来我发现行不通，我的APP的模块是动态加载的，那一开始就注册怎么弄，刚好找到这个方案，不过有点卡。

**Comment by wq13718048209** [comment]
用最新的确实很流畅  不卡  所以我才问作者什么时候接入最新的  而且0.44 以后  以前那个导航已经从react-native里面废除了  单独放在一个包里

**Comment by rilyu** [comment]
react-navigation采用的是路由表方案，与前端开发比较习惯比较吻合，但这需要把所有页面集中管理，我个人看法是这并不是最好的方案，我更倾向于按需引入，每个页面仅import自己需要访问的页面，这样使得页面之间的耦合度降到最小。
Navigator在Debug模式下是有卡顿，但在Release下会好很多，当然页面初始化需要从网络加载数据时还是会卡顿，BasePage的状态isFocused就是为解决这个问题而引入的，可以通过判断this.state. isFocused==true时再渲染耗时较长的组件

**Comment by Lojii** [comment]
直接使用react-navigation配合NavigationPage，会导致页面在安卓上不显示       🤣
