### ISSUE TITLE
Cannot read property 'measure' of undefined

### ISSUE THREAD

**Issue by chuanzhang2018** [rilyu/teaset#173]
使用了AlbumView  ，报错找不到

onImagePress(index){
    
    let pressView = this.refs['it' + index];
    pressView.measure((x, y, width, height, pageX, pageY) => {
      let overlayView = (
        <Overlay.PopView
          style={{}}
          containerStyle={{flex: 1}}
          overlayOpacity={1}
          type='custom'
          customBounds={{x: pageX, y: pageY, width, height}}
          ref={v => this.fullImageView = v}
        >
          <AlbumView
            style={{flex: 1}}
            control={true}
            images={this.state.images}
            thumbs={this.state.images}
            defaultIndex={index}
            onPress={() => this.fullImageView && this.fullImageView.close()}
            />
          <StatusBar animated={false} hidden={true} />
        </Overlay.PopView>
      );
      Overlay.show(overlayView);
    });
  }

 <TouchableOpacity activeOpacity={1} ref={'it' + number} onPress={()=>this.onImagePress(number)}>
        <Image
          key={item.url}
          source={{ uri: image }}
          style={styles.cataloguePhotos}
          resizeMode="cover"
        />
      </TouchableOpacity>

**Comment by pheromone** [comment]
@rilyu  我有出现了这个错误.这个measure哪里的?
