### ISSUE TITLE
在加入PopoverPicker后，只要一打开App就会先闪一下黑色半透明的一个背景

### ISSUE THREAD

**Issue by xy371661665** [rilyu/teaset#176]
只要引入依赖就会出现这个情况

**Comment by xy371661665** [comment]
![Uploading 2018-03-06 11_08_38.gif…]()

效果就是这样的，只要已开启app就会黑屏删一下 @rilyu

**Comment by rilyu** [comment]
图片看不到，黑色的背景是因为Teaset把屏幕默认颜色修改为黑色了，你可以使用 Theme.set({screenColor: '#fff'}) 修改为白色，这样会损失一些页面切换的效果，更合适的做法是在你的应用根组件增加一个铺满屏幕的View，设置这个View的背景色
