### ISSUE TITLE
SegmentedView的SegmentedBar高度改变后，怎么让title上下居中？

### ISSUE THREAD

**Issue by wangfaguo** [rilyu/teaset#180]
render() {

        let dataSource = []

        return (

            <View style={CommonStyle.container}>
                <SegmentedView
                    barStyle={{height: 40}}
                    style={{flex:1}}
                    indicatorLineColor={'#5cb85c'}
                    indicatorLineWidth={2}
                    indicatorPositionPadding={0}
                    onChange={this.segmentOnChange}
                    justifyItem={'scrollable'}
                    indicatorType={'boxWidth'}
                >
                    {dataSource.map((item, index) => this.renderSegmentItem(item, index))}

                </SegmentedView>

            </View>

        );

    }
<img width="267" alt="qq20180312-153904 2x" src="https://user-images.githubusercontent.com/5002018/37270898-8e0a624e-260b-11e8-844d-5bae37e367d6.png">

**Comment by rilyu** [comment]
已修正：https://github.com/rilyu/teaset/commit/98c62b0aef17d470cc5b63c124bd22f293333547
