### ISSUE TITLE
Overlay组件显示问题

### ISSUE THREAD

**Issue by Evai** [rilyu/teaset#181]
比如当前页面有menu overlay，接着从当前页面跳转到下一个页面，然后返回到上一页，就无法显示menu了，除非重新加载组件，这个问题如何解决？所有继承overlay实现的都有这样的问题。

**Comment by rilyu** [comment]
Overlay 是根组件上的顶层组件，隐藏 menu 后需要再次弹出才显示，不隐藏的话在下一个页面也会显示
如果你希望返回到上一页后还显示，那应该在页面上渲染，不能使用 Overlay

**Comment by Evai** [comment]
具体是这样的，tab页面弹出menu，然后再次点击页面其它地方会自动隐藏，这里是没问题的，然后我push了一个页面后，再返回到该页面，点击menu就没反应了，一直不显示。我发现跟导航react native navigation有关系，换成react navigation后就没有这样的问题。这个应该是兼容问题？如果这样，只能使用react navigation了

**Comment by myjbuilddream** [comment]
使用teaset无法使用 Toogle inSpector,无法审查元素
