### ISSUE TITLE
NavigationBar隐藏后下方页面如何上移动

### ISSUE THREAD

**Issue by hsessay** [rilyu/teaset#182]
```
renderNavigationBar() {
    return (
      <NavigationBar 
        hidden={true}   />
    );
  }
```

用上面方法实现导航栏隐藏之后，视图顶部留出了导航栏高度的空白距离，请问这里需要怎么才能让视图网上移动呢？
![987d2a9e-3663-4e22-aa46-03063b4abed2](https://user-images.githubusercontent.com/5794389/37328893-aa53f840-26d6-11e8-8528-b7b8e6b758b0.png)

**Comment by rilyu** [comment]
navigationBarInsets=false

**Comment by hsessay** [comment]
谢谢！
