### ISSUE TITLE
NavigationPage配合KeyboardAwareScrollView使用页面异常

### ISSUE THREAD

**Issue by hsessay** [rilyu/teaset#183]
登录页面NavigationPage与KeyboardAwareScrollView配合使用，NavigationBar隐藏时，页面无法正常回到起始位置，效果如下

键盘弹出前
![d1c97d40-4c51-4d71-8eae-2398ea0ee48c](https://user-images.githubusercontent.com/5794389/37392647-ac051b14-27a9-11e8-83ea-b40aaad7e08f.png)

键盘反复弹出收起后

![d1c97d40-4c51-4d71-8eae-2398ea0ee48c](https://user-images.githubusercontent.com/5794389/37392647-ac051b14-27a9-11e8-83ea-b40aaad7e08f.png)

![034a1d68-5e4a-404d-8b20-cc9d7f3179be](https://user-images.githubusercontent.com/5794389/37392667-c42f2a4a-27a9-11e8-948d-0ccf7f85317a.png)

**Comment by rilyu** [comment]
NavigationPage 已经集成了避免键盘遮挡功能，没必要使用KeyboardAwareScrollView，使用普通的 ScrollView 就可以了；
如果还是想使用 KeyboardAwareScrollView ，NavigationPage 的 autoKeyboardInsets 属性传入 false；
不需要导航条可使用 BasePage ，而不是 NavigationPage。

**Comment by hsessay** [comment]
请问一下如果基础视图是View的情况下该怎么处理键盘遮挡呢？

**Comment by rilyu** [comment]
你确认键盘弹出来之后所有必要信息都能显示完整可以不使用 ScrollView，容器 View 指定 flex=1，在容器View内上中下放3个组件，中间的是内容组件，指定 height ，上下各放一个空间占用 View ，指定 flex 分配空间比例

**Comment by hsessay** [comment]
谢谢！
