### ISSUE TITLE
menu菜单遍历取值问题

### ISSUE THREAD

**Issue by sideme** [rilyu/teaset#184]
问题如下：
当我遍历menu菜单时，发现onPress事件每次触发的都是最后一个值，这是我的代码，请问哪里写错了吗？
![image](https://user-images.githubusercontent.com/10138628/37398172-9682807e-27b8-11e8-872b-c6f4d794656d.png)

**Comment by sideme** [comment]
alert每次触发最后一个itemTitle获取的值，但是title显示是正常的按顺序显示

**Comment by rilyu** [comment]
你把代码中3个var换成let

**Comment by sideme** [comment]
不好意思。。。
