### ISSUE TITLE
Input设置disabled还能聚焦

### ISSUE THREAD

**Issue by tong233** [rilyu/teaset#185]
你好，很棒的ui，我有几个问题和建议。
1.Input设置disabled无效，android 6.0和7.1，加editable就行了，但是editable没有透明的效果，禁用的时候能设backgroundColor就好了，区分明显一点。
2.ListRow detail里的内容怎么居左比如Switch。
3.Input输入框右边能加一个清除小叉叉吗，在clearButtonMode不支持android的情况下。
![image](https://user-images.githubusercontent.com/21073132/37441567-0baf42d6-283d-11e8-9e5d-fc8811bb0e13.png)

**Comment by rilyu** [comment]
Input 继承自 TextInput ，作了外观的统一性封装，这个问题只能等 React Native 修正；
ListRow detail 可以这样实现居左：<View style={{flex:1}}>...</View>

**Comment by tong233** [comment]
...是怎样

**Comment by rilyu** [comment]
显示不出来，就是使用一个style设置了flex=1的View把你的detail包裹起来，类似这样
```
<View style={{flex:1}}>
  <Text>Detail</Text>
</View>
```

**Comment by tong233** [comment]
好的,谢谢
