### ISSUE TITLE
Sample安装失败，执行npm install出现以下错误

### ISSUE THREAD

**Issue by zengqingsong** [rilyu/teaset#191]
npm WARN tar ENOENT: no such file or directory, open 'D:\Nodejs\ReactNative\teaset\example\node_modules\.staging\react-native-d46608c2\Libraries\Settings\RCTSettings.xcodeproj\project.pbxproj'
npm WARN tar ENOENT: no such file or directory, open 'D:\Nodejs\ReactNative\teaset\example\node_modules\.staging\react-native-d46608c2\Libraries\Settings\RCTSettingsManager.h'
npm WARN tar ENOENT: no such file or directory, open 'D:\Nodejs\ReactNative\teaset\example\node_modules\.staging\react-native-d46608c2\Libraries\Settings\RCTSettingsManager.m'
npm ERR! Unexpected end of JSON input while parsing near '...e":"readable-stream",'

**Comment by rilyu** [comment]
应该是环境问题，我这没有 Windows，你可以试试升级 npm 或其它方法

**Comment by zengqingsong** [comment]
已经解决。

**Comment by hms111111** [comment]
怎么解决的?
