### ISSUE TITLE
Overlay不能通过setState进行数据更新问题

### ISSUE THREAD

**Issue by whiteMu** [rilyu/teaset#197]
Overlay是用给的例子写的，但是我更改了state里的值，但是Overlay的界面是不更新的，这个怎么解决？

**Comment by rilyu** [comment]
Overlay 从根组件弹出，并没有加入当前组件的 DOM 树中，因此当前组件的状态无法影响到 Overlay 的 view，换句话说， 目前 Overlay 弹出的 view 需要自己维护状态。
从提出的 Issues 来看，这个功能还是挺有必要的，Redux 也是如此，我考虑一下看是否有好的办法实现。

**Comment by whiteMu** [comment]
请问您说的目前 Overlay 弹出的 view 需要自己维护状态是怎么维护？是写入一个组件自己setState去更改吗？请问有demo吗？因为您这边需要将Overlay传入才能show出来，所以不知道该如何去写

**Comment by ArlenWang** [comment]
我也遇到这个问题，无办法Redux,只能用modal实现我的抽屉

**Comment by ArlenWang** [comment]
modal也有不足的地方，自动强制出现StatusBar

**Comment by whiteMu** [comment]
你有什么类似的插件吗？

**Comment by ArlenWang** [comment]
我直接用页面跳转了。

2018-04-14 9:27 GMT+08:00 whiteMu <notifications@github.com>:

**Comment by whatlife** [comment]
@rilyu 目前有实现这个问题了吗

**Comment by rwgao** [comment]
@whiteMu 我目前也遇到这个问题，请问您现在这个问题解决了吗？如何解决的。

**Comment by whiteMu** [comment]
@rwgao 我直接将需要Overlay展示的内容写入一个组件，组件自己进行更新。
<Overlay.PullView>
    <自己定义的组件
        需要传入的数据/方法等
    />
</Overlay.PullView>

**Comment by luckyzwei** [comment]
> @rwgao 我直接将需要Overlay展示的内容写入一个组件，组件自己进行更新。
> <Overlay.PullView>
> <自己定义的组件
> 需要传入的数据/方法等
> />
> </Overlay.PullView>

请问数据如何传入，因为是Overlay是show的参数，这个咋写。

**Comment by kluas11** [comment]
有解决方案吗？

**Comment by doKill** [comment]
不了解作者有没有什么办法，我目前是Overlay内部组件维护自己的状态，变更时用传进组件的方法同步一下
