### ISSUE TITLE
Can you put this library to npm?

### ISSUE THREAD

**Issue by qurbanliwayidin** [rilyu/teaset#198]
Can you please put this library to nmp? I can not access to GutHub sometimes and can not download from it. Thanks.

**Comment by qurbanliwayidin** [comment]
It would be wonderful if this can be downloaded via npm.

**Comment by rilyu** [comment]
You can install teaset via npm:
```
npm install --save teaset
```
package link: https://www.npmjs.com/package/teaset

but, teaset depends on react-native-deprecated-custom-components package, and it is no longer published to npm with react-native upgrade, then you need to connect to github to download the latest react-native-deprecated-custom-components package
