### ISSUE TITLE
TabView

### ISSUE THREAD

**Issue by wq13718048209** [rilyu/teaset#20]
我使用TabView  从当前页跳转到 另外一页  底部的TabView  一直都在  有什么方法让他隐藏吗

**Comment by rilyu** [comment]
TabView的行为就是这样的，典型的ios app风格，点击跳到新的页面应该叫ToolBar吧，自己写一个也简单

**Comment by rilyu** [comment]
现在已经支持了，TabView.Sheet 设置属性 type='button' 即可
