### ISSUE TITLE
单独使用Menu组件，屏幕上会有一个透明的黑色浮层

### ISSUE THREAD

**Issue by z372183629** [rilyu/teaset#21]
截图的链接
[http://wx3.sinaimg.cn/mw690/900bfde3ly1fgw6iqzyisj20u01hc763.jpg](url)

如果我的页面继承自BasePage 就没有问题，但是继承Component的页面会有这样的效果。

**Comment by rilyu** [comment]
这是因为Teaset把屏幕颜色设置为 #444 灰色了，有两个方法可以解决，一是给你的组件设置一个背景色并占满屏幕，二是在代码入口位置设置你需要的颜色，见下：
```
Theme.set({
  screenColor: '#fff',
});
```

**Comment by z372183629** [comment]
原来是背景色的问题，哈哈，大意了。。。。。
