### ISSUE TITLE
AlbumView可以加一个回收和预加载机制吗

### ISSUE THREAD

**Issue by qq326646683** [rilyu/teaset#216]

**Comment by rilyu** [comment]
AlbumView 有预加载机制，当前图片的前一张、后一张均会预加载，但没有回收机制，测试时发现ReactNative显示较大的图片延迟比较严重，因此就把回收功能取消了
如果需要回收图片版本，可以使用 AlbumView 目录下的 AlbumView.deprecated.js ，属性、使用方法是一样的，一次最多加载三张图片，超出范围将释放掉，在显示较大图片时会有延迟。

**Comment by danna88** [comment]
你好，请问下，你用这个组件后，有没有发现，左右滑动不是很灵敏？ 感觉要滑动到某一个位置才跳地过去。

**Comment by qq326646683** [comment]
album-view.js里onWillMagnetic变量triggerWidth控制的滑动屏幕的几分之几做跳转。
如果想快速也翻页，你可以在这个方法稍作改动：
let timeDx = new Date().getTime() - this.startSlideTime
    let currentSpeed = ltx / timeDx
    if (scale < 1) {
      return true
    } else if (timeDx < 200) {
      if (index !== 0 && currentSpeed > changePageSpeed) {
        this.changeIndex(index - 1)
        return false
      } else if (index !== images.length - 1 && currentSpeed < -changePageSpeed) {
        this.changeIndex(index + 1)
        return false
      } else {
        if (index > 0) lastSheet.scrollX(0, true)
        if (index < (images.length - 1)) nextSheet.scrollX(0, true)
        return true
      }
    } 
@danna88
