### ISSUE TITLE
请教,关于传参的问题？

### ISSUE THREAD

**Issue by shaonq** [rilyu/teaset#22]
页面类的组件很好用，但是不知道依赖于这也页面组件的页面如何处理传参。

**Comment by rilyu** [comment]
就按一般的RN组件传参方式就可以了，入参使用属性传入，返回参数使用回调函数传出，例：
```javascript
this.navigator.push({view: <TestPage title='Test' onSubmit={value => this.onTestSubmit(value)}/>});
```

**Comment by shaonq** [comment]
this.navigator.push({view: <AboutPage  testDate={{data:{user:"user",name:"name"}}}
` 
    constructor(props) {
        super(props);
        console.log(this.props.testDate);
 }
`
可以看到数据。

`    componentDidMount() {
        this.interval = setInterval(() => {
            this.setState({
                timerCount: this._format(new Date())
            })
        }, 500)
    }
    componentWillUnmount() {
        clearInterval(this.interval)
    }
`
但是，模拟器放置一段时间后，报抛出异常的错误。

**Comment by rilyu** [comment]
你在componentDidMount、componentWillUnmount加点日志看看这两个函数调用是不是成对出现，我记得从下层页面pop返回时会调用componentDidMount，但push时却不会调用componentWillUnmount，这样就会导致上一次的this.interval不会被clear，你加日志检查一下是不是这样

**Comment by shaonq** [comment]
粗略的测试了一下，是成对出现，关于pop调用的问题，后续写代码的时候会留意。
目前的做法也是，
```
componentWillUnmount() {
        this.interval&&clearInterval(this.interval)
}
```
也猜测了 `this.interval` 未声明的问题；
```
var a={}   //Object {}
clearInterval(a.b)  //undefined
```
目前未出现错误。
