### ISSUE TITLE
toast duration error

### ISSUE THREAD

**Issue by XueChenChen** [rilyu/teaset#23]
code: 
```js
static show(options) {
    let {duration, ...others} = options && typeof options === 'object' ? options : {};

    let key = super.show(<this.ToastView {...others} />);
    if (typeof duration !== 'number') {
      console.log("Toast--duration");
      switch (duration) {
        case 'long': duration = 3500; break;
        default: duration = 7000; break;
      }
    }
    console.log("Toast--duration-time ", duration);
    console.log("Toast--duration-time-dataStart", new Date());
    setTimeout(() => {
      console.log("Toast--duration-time-dataEnd", new Date());
      this.hide(key)
    }, 7000);

    return key;
  }
```

error:
>Toast--duration
E:\lottery\RNLotteryProject\node_modules\teaset\components\Toast\Toast.js:40 Toast--duration-time  7000
E:\lottery\RNLotteryProject\node_modules\teaset\components\Toast\Toast.js:41 Toast--duration-time-dataStart Sat Jul 08 2017 10:02:37 GMT+0800 (中国标准时间)
E:\lottery\RNLotteryProject\APP\Buy\BuyMainPage.js:53 paresData
E:\lottery\RNLotteryProject\APP\Buy\BuyMainPage.js:336 redner 
E:\lottery\RNLotteryProject\APP\Buy\BuyMainPage.js:141 createNowLotteryNumberView 00 04 02 33 11 55 11
E:\lottery\RNLotteryProject\APP\Buy\BuyMainPage.js:336 redner 
E:\lottery\RNLotteryProject\APP\Buy\BuyMainPage.js:336 redner 
E:\lottery\RNLotteryProject\node_modules\teaset\components\Toast\Toast.js:43 Toast--duration-time-dataEnd Sat Jul 08 2017 10:02:37 GMT+0800 (中国标准时间)
E:\lottery\RNLotteryProject\node_modules\teaset\components\Toast\Toast.js:43 Toast--duration-time-dataEnd Sat Jul 08 2017 10:02:37 GMT+0800 (中国标准时间)

**Comment by rilyu** [comment]
请确认是否使用了第三方的定时器类组件，Teaset没有重写setTimeout函数，如果是setTimeout定时不准确，那很可能是与第三方定时器冲突了，请在一个比较干净的工程里测试验证一下
