### ISSUE TITLE
安卓真机页面跳转，会有延迟而且不丝滑，甚至卡顿

### ISSUE THREAD

**Issue by xiao0502** [rilyu/teaset#232]
页面跳转点击后，过零点几秒后才执行跳转动画，而且一些配置一般的安卓机上，从右往左的动画卡顿的厉害

**Comment by rilyu** [comment]
一般卡顿的原因是在页面跳转的过程中作了一些比较耗时的操作，比如下一个页面在初始化时访问网络、渲染页面，可以在转场完成后再做这些操作，BasePage、NavigationPage会在转场完成后调用 onDidFocus 函数，可以重载这个函数处理，或者使用 this.state.isFocused 判断

**Comment by xiao0502** [comment]
我用react-navigation就没有出现卡顿的情况，我的网络请求和页面渲染都是放在actionManager.runAfterInteractions的回调去执行的
