### ISSUE TITLE
hope for a component like this

### ISSUE THREAD

**Issue by ijry** [rilyu/teaset#233]
![simulator screen shot - iphone 6 - 2018-05-10 at 00 05 37](https://user-images.githubusercontent.com/3102798/40033686-0e37acae-582c-11e8-8ef0-03cd39f8b53c.png)

**Comment by ijry** [comment]
and 登录 can align center

**Comment by pingxiaodou** [comment]
这个用现有的input和listrow就可以实现啊，自定义下样式就可以

**Comment by ijry** [comment]
是可以但是有奇怪的bug。

发自我的 iPhone
