### ISSUE TITLE
安装不了呢，我用npm和yarn都尝试了，还是失败。

### ISSUE THREAD

**Issue by ChrisDowney1996** [rilyu/teaset#235]
npm:
D:\idea-workspace\react-native\CustomNav>npm install --save teaset
npm ERR! Error while executing:
npm ERR! F:\OfficeProgram\git\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/facebookarchive/react-native-custom-components.gi
t
npm ERR!
npm ERR! ssh_exchange_identification: Connection closed by remote host
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2018-05-15T10_13_56_170Z-debug.log

D:\idea-workspace\react-native\CustomNav>npm install --save teaset
npm ERR! Error while executing:
npm ERR! F:\OfficeProgram\git\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/facebookarchive/react-native-custom-components.gi
t
npm ERR!
npm ERR! ssh_exchange_identification: Connection closed by remote host
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!

yarn:
D:\idea-workspace\react-native\CustomNav>yarn add teaset
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/facebookarchive/react-native-custom-components.git HEAD
Directory: D:\idea-workspace\react-native\CustomNav
Output:
fatal: unable to access 'https://github.com/facebookarchive/react-native-custom-components.git/': OpenSSL SSL_connect: SSL_ERROR_SYS
CALL in connection to github.com:443
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

远程服务器关闭？

**Comment by my4piano** [comment]
我直接下载作者的demo，在 example 的基础上进行开发，这样不会出错

**Comment by shuiRong** [comment]
我也遇到了同样问题：安装Teaset不上
![image](https://user-images.githubusercontent.com/16076993/54588945-4fa3e380-4a5f-11e9-914e-32bec9a9ca36.png)

不是翻墙的问题，因为其他依赖安装没问题，并且我也尝试过[端口设置](https://github.com/yarnpkg/yarn/issues/3418#issuecomment-301892013)。

**Comment by jjasoncool** [comment]
使用 corepack enable 的 yarn 似乎無法正確設定 proxy
需要使用 npm install --global yarn 才可以正常設定
![2022-02-23_nodejs_network](https://user-images.githubusercontent.com/24731867/156119190-1b7e19e9-9000-4e7c-b921-31f9d1996908.png)

**Comment by zsswlr** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
