### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by wq13718048209** [rilyu/teaset#24]
已经不再更新了吗 作者?

**Comment by rilyu** [comment]
会更新的，React Native官方更新太频繁，我个人无法投入那么多时间跟上官方的进度，积累几个版本再更新一版，这个月会更新一版

**Comment by wq13718048209** [comment]
恩 是的 更新确实频繁  还有就是 为啥我用自己写的弹出框不卡  引入你的组件  用了几个简单的浮层  就可的很厉害  我觉得不应该啊  不就是几个动画的效果吗
