### ISSUE TITLE
在使用相册视图,不能使用uri:XX来加载图片吗?

### ISSUE THREAD

**Issue by pheromone** [rilyu/teaset#249]
如下:如果我使用uri来会报这个错误,如果使用本地图片的话就是正常的.难道只能使用本地图片吗?
![image](https://user-images.githubusercontent.com/14305431/41215326-6e527892-6d82-11e8-9bb7-e329ac9de2e5.png)

**Comment by rilyu** [comment]
images属性应该传入数组，类似这样
```
<AlbumView
  images={[{uri: 'http...', uri: 'http...', ]}
  />
```

**Comment by pheromone** [comment]
太谢谢.终于好了
