### ISSUE TITLE
关于导航功能

### ISSUE THREAD

**Issue by my4piano** [rilyu/teaset#25]
我在index.android.js使用了 TabView
`export default class TabViewExample extends BasePage {

  static defaultProps = {
    ...BasePage.defaultProps,
    scene: TeaNavigator.SceneConfigs.PushFromRight,
  };

  constructor(props) {
    super(props);
    Object.assign(this.state, {
      type: 'projector',
    });
  }

  renderPage() {
    return (
      <TabView style={{ flex: 1 }} type={this.state.type} >
        <TabView.Sheet
          title='主页'
          icon={require('./icons/my/home.png')}
          activeIcon={require('./icons/my/home_fill.png')}
        >
          <HomePage />
        </TabView.Sheet>`
当我进入一个tab后，点击一个按钮，然后整个tabview导航到别的页面，请问这种效果怎么做？

拿微信举个例子，点击“发现”->"朋友圈"

**Comment by rilyu** [comment]
这个功能在Example中的[Home.js](https://github.com/rilyu/teaset/blob/master/example/views/Home.js)就有，大致是这样：
```javascript
export default class Home extends NavigationPage {

  static defaultProps = {
    ...NavigationPage.defaultProps,
    title: '发现',
  };

  renderPage() {
    return (
      <ScrollView style={{flex: 1}}>
        <ListRow title='朋友圈' onPress={() => this.navigator.push({view: <YourPageClass />})} />
      </ScrollView>
    );
  }
}
```

**Comment by my4piano** [comment]
你这个例子我知道，但是并没有使用 TabView，在TabView中添加一个组件，其属性为 onPress={() => this.navigator.push({view: <Moments />})}

所导航的是TabView的子页，而不是整个TabView，我需要实现的效果是后者
