### ISSUE TITLE
SegmentedView 设置activeIndex后 工具条不切换

### ISSUE THREAD

**Issue by ackasync** [rilyu/teaset#256]
![default](https://user-images.githubusercontent.com/14857194/42209258-c8ab129e-7ee0-11e8-8bf5-7e8ab6eb0b74.png)

    如图所示，设置activeIndex的默认值后。点击其他Item不会激活。除非自己实现onChange动态修改activeIndex的值。
    是否应该修改源码中 get activeIndex(){...} 的实现？

    get activeIndex() {
      let activeIndex = this.props.activeIndex;
      if (activeIndex || activeIndex === 0) return activeIndex;
      else return this.state.activeIndex;
    }

**Comment by rilyu** [comment]
使用 activeIndex 属性需要自行在 state 中管理
```javascript
    activeIndex: PropTypes.number, //if use this prop, you need update this value from onChange event
```
例
```javascript
...
this.state = {
  activeIndex: 3,
}
...
<SegmentedView
  activeIndex={this.state. activeIndex}
  onChange={index => this.setState({activeIndex: index})}
  />
...
```

**Comment by zth15378** [comment]
我也遇到了这个问题， 不设置activeIndex 就没问题。
