### ISSUE TITLE
请教，PopoverPicker可以暴露一个能够手动隐藏的方法吗

### ISSUE THREAD

**Issue by lhaiqing** [rilyu/teaset#26]
![image](https://user-images.githubusercontent.com/18346361/28416272-f407ae60-6d85-11e7-9811-9555a1c42be5.png)
只有一个show方法，而隐藏方法close()需要继承浮层OverlayView或者继承自OverlayView的子类。。

**Comment by rilyu** [comment]
所有浮层静态类均派生自Overlay，继承了Overlay.hide方法
let key = PopoverPicker.show(...);
PopoverPicker.hide(key);
