### ISSUE TITLE
关于Checkbox的扩展

### ISSUE THREAD

**Issue by giantss** [rilyu/teaset#262]
目前想实现两个功能：
1，长按。
2，选中的数量限制。（比如只允许用户最多选择三项，功能是实现了，但是当用户在选择第4项的时候虽然我可以提示逻辑也可以，但是选了第项按钮UI上还是展示为已选中状态，设置checked={false}根本无效啊）

请教🙏
@rilyu

**Comment by rilyu** [comment]
在 Checkbox 的 onChange 事件判断已选项数，修改相应项的checked并setState，Checkbox的checked属性要从state中取

**Comment by giantss** [comment]
额，我自己扩展了一个checkbox组件
