### ISSUE TITLE
请问下，A->B->C 的页面，怎么从C 直接跳转回A，或者说是从C 跳转到rootView

### ISSUE THREAD

**Issue by SongBana** [rilyu/teaset#290]
请问下，A->B->C 的页面，怎么从C 直接跳转回A，或者说是从C 跳转到rootView

**Comment by SongBana** [comment]
看到了，需要看React 的navigator组件。http://www.hangge.com/blog/cache/detail_1741.html

**Comment by zsswlr** [comment]
这个库不是有封装的吗？  this.navigator.push（{view：<index/>}）

**Comment by SongBana** [comment]
@zsswlr 我要的跳到指定页面，封装的 只有push和pop

**Comment by SongBana** [comment]
@zsswlr 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/26177426/45066770-7d908e80-b0f2-11e8-85b0-f1eb4b966a49.png">
这个库的navigator是基于 React 的navigator 的，所以 react的这些属性也可用的
