### ISSUE TITLE
可否自定义弹出视图？

### ISSUE THREAD

**Issue by erhutime** [rilyu/teaset#3]
1-：感觉功能比较强大，但是项目中只会用一两个，想拆出来，发觉包还是很大的。
2-：可否自定义弹出内容？view视图是否提供自定义？

**Comment by erhutime** [comment]
另，仔细查看代码，发现，此乃神人也。代码逻辑如此严谨，清晰。

**Comment by rilyu** [comment]
1、 设计时所有组件都是可以单独使用的，比如只使用Label：
```
import Label from 'teaset/components/Label/Label';
```
不过我没有测试过，你可以试试看，应该是可以的。

2、可以弹出任何内容，具体可参考OverlayExample.js，查看Overlay.js可以看出来Overlay.show的参数没有任何限制，可以是任何View，不过我建议弹出的View继承自Overlay.View并加上自己的逻辑，Overlay.PullView, Overlay.PopView, Overlay.PopoverView就是这么做的；
Overlay.View, Overlay.PullView, Overlay.PopView, Overlay.PopoverView是Overlay的静态变量，意味着你可以替换成你自己的class以改变弹出层的默认样式和行为，例如：
```
Overlay.View = MyOverlayView;
```

**Comment by erhutime** [comment]
大神，目前有一个需求，想用你的来实现。就是点击Listview的item某一个控件，然后点击的item的控件旁边展示一个弹出层，弹出层高亮，屏幕其他弹出层遮罩，变灰。想用你这个来实现，不知道如何下手，大神可有思路，求指导。

**Comment by rilyu** [comment]
不知道这是不是你想要的效果：
```
<ListRow title='测试左边弹出' detail={
  <Button title='点我弹出' ref='popoverButton' onPress={() => this.onPopoverButtonPress()} />
} />

onPopoverButtonPress() {
  this.refs['popoverButton'].measureInWindow((x, y, width, height) => {
    let fromBounds = {x, y, width, height};
    let overlayView = (
      <Overlay.PopoverView
        fromBounds={fromBounds}
        direction='left'
        align='start'
        directionInsets={4}
        showArrow={false}
        overlayOpacity={0.4}
      >
        <View style={{height: 60, padding: 10}}>
          <Label size='lg' text='这是内容' />
        </View>
      </Overlay.PopoverView>
    );
    Overlay.show(overlayView);
  });
}
```
如果是，把
```
        <View style={{height: 60, padding: 10}}>
          <Label size='lg' text='这是内容' />
        </View>
```
替换成你要显示的内容就行了

**Comment by erhutime** [comment]
您好，我遇到一些问题：
1-：_renderRow(rowData) {
        return (
            <GoodInCell
                msg='GoodInCell'
                rowData={rowData}
                onSelected={()=>{
                    this.onPopoverButtonPress();
                }}
                onSelectedByType={(type)=>{
                    this._onSelectedByType(type)
                }}
            />
        );
    }
2-：GoodinCell:
let refMsg=this.props.msg;

<TouchableOpacity
                            ref={refMsg}
                            onPress={()=>{
                                this.onSelected();
                            }}>
                            <Image source={require('../../images/icon_time.png')} style={styles.iconBtn} />
                        </TouchableOpacity>
2-:点击弹出方式还是按照你给的代码进行了简单修改，
点击时：
undefined is not an object (evaluating 'this.refs['GoodInCell'].measureInWindow')
排查不到问题，大神，有遇到类似的吗？

**Comment by erhutime** [comment]
问题已经解决，谢谢大神，之前提供的方式可行。

**Comment by Gqq475** [comment]
很好  如有需要 会选择的
