### ISSUE TITLE
Input 组件设置多行无效

### ISSUE THREAD

**Issue by siroer** [rilyu/teaset#30]
`<Input
                    multiline={true}
                    numberOfLines={4}
                    onChangeText={(text) => this.setState({ text })}
                    value={this.state.text}
/>`

**Comment by rilyu** [comment]
设置高度试试
```
<Input style={{height: 120}} multiline={true} numberOfLines={4} onChangeText={(text) => this.setState({ text })} value={this.state.text} />
```
