### ISSUE TITLE
关于react-native-deprecated-custom-components的问题

### ISSUE THREAD

**Issue by Aaronnnnn** [rilyu/teaset#309]
"react": "16.6.0-alpha.8af6728",
"react-native": "^0.57.3",
"teaset": "^0.5.9"
更新了xcode10以后，在启动的时候，会报下图错误
![dc06afc8-7ac0-4d78-a90e-e9172cefa9db](https://user-images.githubusercontent.com/24308182/47140185-37813a00-d2f0-11e8-9b32-8c7e282be828.png)

**Comment by winterwd** [comment]
这个不是已经标明  弃用 了呀？怎么还在用？

**Comment by rilyu** [comment]
最新版已把该依赖包发布到 npm ，不再依赖 github https://github.com/rilyu/teaset/commit/645a1dbcd6621a6624c4dbc2176ed87469323010
