### ISSUE TITLE
弹窗里面再弹窗

### ISSUE THREAD

**Issue by orzhtml** [rilyu/teaset#31]
A弹窗的Input给了  this.state.xxx
点击A的某个按钮弹出B弹出（A弹窗不关闭）
B弹出某个按钮点击后 改变 this.state.xxx 的值，后关闭B弹窗
A弹窗里面的  this.state.xxx 没改变。
求如何改变值

**Comment by rilyu** [comment]
你在弹出B时传入A修改State的事件函数，然后在B里点击按钮时调用这个事件函数修改A的对应的状态值
一般就是这种做法，比如Button，你不能在Button内去修改任何一个页面的状态，而是在Button.onPress事件函数修改页面的状态
