### ISSUE TITLE
TeaNavigator yellowbox warning "Require Cycle"

### ISSUE THREAD

**Issue by hefengxian** [rilyu/teaset#318]
### 使用场景

有 3 个文件

- `index.js` 程序入口使用 `TeaNavigator`
- `Login.js` 登录页面
- `Home.js` 主页，需要登录之后访问

使用 teaset 内置的 navigator 作为导航, `index.js` 中

```jsx
import Login from './screens/Login'
/* 其他代码... */

export default class App extends React.Component {
    render () {
        return (
            <TeaNavigator rootView={<Login />}/>
        )
    }
}
```

1. `Login.js` 登录请求成功后需要跳转到 `Home.js`，那么在 `Login.js` 中需要如下语句来跳转

```jsx
// 引入 Home
import Home from './Home'
/* 其他代码... */

export default class Login extends BasePage {
    /* 其他代码... */

    // 登录方法
    login = () => {
        // Login ... 
        // 跳转到 Home
        this.navigator.resetTo({view: <Home />})
    }
}
```
2. `Home.js` 中有个登出按钮，点击之后清除认证信息之后需要跳转到 `Login.js`，那么在 `Home.js` 需要如下语句来完成登出跳转

```jsx
// 引入 Login
import Login from './Login'
/* 其他代码... */

export default class Home extends BasePage {
    /* 其他代码... */

    // 登录方法
    logout = () => {
        // clear OAuth ...
        // 跳转到 Home
        this.navigator.resetTo({view: <Login />})
    }
}
```

### 导致的问题

如上就导致出现了 YellowBox 警告 `Require cycle ....`，因为在这里

```
这两个组件相互依赖

Login -> import Home
Home -> import Login
```

像 `react-navigation` 组件因为路由是先声明的，就不会有这种问题；请问在使用 `TeaNavigator` 时，有什么方案可以解决这种场景吗？

> 虽然 YellowBox 警告并不会影响构建之后的使用，功能也能正常运行；但是仍然有这样的警告。

**Comment by rilyu** [comment]
```
<TeaNavigator rootView={<Login />}/>
```
不建议这么使用，根节点不应该是Login，一般应该是 Home 或别的名称的一个组件，在这个组件内维护登录状态，未登录时使用条件渲染(强制必须登录)或者弹出登录页面(某些页面需要登录)，这样不不存在 Require cycle 问题

**Comment by rilyu** [comment]
从 Login 直接跳 Home 是一种强耦合方案，对于 Login 这种通用功能来说不是好的解决方案。
你可以在 AuthLoading 处理登录逻辑, Login 提供一个回调函数属性，比如 onLogin ，在这个回调函数里处理登录后的逻辑，比如跳转到 Home 。

**Comment by hefengxian** [comment]
@rilyu 可能只能用事件了吧，那我关了这个 issue 吧
