### ISSUE TITLE
<ModalIndicator>覆盖问题?

### ISSUE THREAD

**Issue by zhuanglong** [rilyu/teaset#32]
我用的是react-navigation,
<ModalIndicator.IndicatorView/>不能覆盖导航栏，
ModalIndicator.show()则可以覆盖，但是在render()中使用会有以下警告：
Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

**Comment by rilyu** [comment]
你应该是在 `render` 函数里调用 `ModalIndicator.show()` 了，按提示移到 `componentWillMount` 即可

**Comment by zhuanglong** [comment]
我想问下为什么ModalIndicator.show()可以覆盖导航栏，
还有buildProps()，renderContent()，
get text()，set text(value)这种写法我没见过，
小白请指教。

**Comment by rilyu** [comment]
ModalIndicator.show 使用了 Overlay 的功能，通过重写 React Native 的 AppRegistry.registerComponent 函数实现顶层覆盖，具体参考 TopView.js
buildProps()，renderContent() 是自定义的普通函数，是 Teaset 的约定名称
get text()，set text(value) 这是 ES6 的 getter 和 setter ，可以参考一下 ES6 的文档

**Comment by zhuanglong** [comment]
@rilyu 非常感谢！

**Comment by s349856186** [comment]
@rilyu 请教下这个ModalIndicator组件有办法覆盖(react-navigation)导航栏吗？想实现界面中心显示loading时，底部导航tab可以点击的效果，谢谢
