### ISSUE TITLE
Warning: Expected instance props to match memoized props before componentDidMount. This is likely due to a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by orzhtml** [rilyu/teaset#321]
问题：
Warning: Expected instance props to match memoized props before componentDidMount. This is likely due to a bug in React. Please file an issue.
其中一种复现方式：
调用
import { Overlay } from 'teaset';
创建出一个弹窗 componentDidMount 触发弹窗，然后就会出现上面的问题警告
其中一种复现方式：
import { Drawer } from 'teaset';
创建一个侧栏，触发侧栏，然后就会出现上面的问题警告
此处省略多种使用 teaset 组件后会提示警告的情况 
 "teaset": "^0.5.10"

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 27.21 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: EAP AI-171.4010489 AI-171.4010489
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      eslint-plugin-react-native: 3.5.0
      react-native-cli: 2.0.1

**Comment by zt5** [comment]
+1 只放个按钮都会触发这个问题 应该是RN0.57改了什么东西导致的

**Comment by houdangdang** [comment]
+1 the same problem

**Comment by dgleung** [comment]
同样问题 react 16.6.1  native 0.57.7

**Comment by suyuja** [comment]
遇到了同样的问题，请问这个问题如果解决？

**Comment by huangguoqin** [comment]
有人解决这个问题了吗？

**Comment by yanqiqi1996** [comment]
同样的问题。没去管它

**Comment by orzhtml** [comment]
0.6.0 已经解决该问题，现在关闭。
