### ISSUE TITLE
Can't NavigationBar and SegmentedView be used together

### ISSUE THREAD

**Issue by yrjwcharm** [rilyu/teaset#329]
<View style={{flex:1,backgroundColor:'#f5f5f5',}}>
                <Title name="进度查询"/>
                <SegmentedView
                    style={{flex: 1,}}
                    type={this.state.type}
                    indicatorLineColor={'#5e91fd'}
                    indicatorLineWidth={ 2}
                    indicatorPositionPadding={ 0 }
                    activeIndex={this.state.activeIndex}
                    onChange={index => this.setState({activeIndex: index})}
                >
                    <SegmentedView.Sheet title={this.renderTitle(0)}>
                        <ToDo/>
                    </SegmentedView.Sheet>
                    <SegmentedView.Sheet title={this.renderTitle(1)}>
                        <AllProgressQuery/>
                    </SegmentedView.Sheet>
                </SegmentedView>
            </View>

我的title 里放的是NavigationBar 但是这两者有冲突 。。如果NavigationBar 有显示的话 。。SegmentedView 就显示不出来。。

**Comment by cnpmge** [comment]
请问你是这么解决的？我是动态加载的这个组件，并不显示title
![Screenshot_2019-08-22-12-55-02-203_com xiaoliao](https://user-images.githubusercontent.com/48587696/63486974-1ecb4d00-c4dc-11e9-87bf-18681c37d673.png)

**Comment by yrjwcharm** [comment]
你看文档 啊。
