### ISSUE TITLE
在方法里面弹出Overlay，界面内容怎么根据state改变？

### ISSUE THREAD

**Issue by fanyongbing** [rilyu/teaset#33]
在Overlay浮层里面使用this.state.xxx
然后在其他地方修改了状态，界面内容不更新，在线等答案

**Comment by rilyu** [comment]
Overlay 没有被设计用于复杂的页面间数据交互，弹出 Overlay 的组件的状态改变不会引起 Overlay 重新 render
如果你确实需要这么用，可以使用 ref 保存弹出的视图组件，然后在 this.state 发生改变时调用该组件提供的刷新函数，可参考 https://github.com/rilyu/teaset/tree/master/components/ModalIndicator
这个组件就是从外部更改了 Overlay 里的组件的内容，见 https://github.com/rilyu/teaset/blob/master/example/views/ModalIndicatorExample.js
