### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by XHTeng** [rilyu/teaset#338]
error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/sean/文档/project/Flavours_4.0/node_modules/teaset/components/ListRow/node_modules/teaset/icons'

**Comment by tourze** [comment]
我也遇到这个问题了。。。请问怎么解决的？

**Comment by XHTeng** [comment]
重启电脑就好了

**Comment by 131986777** [comment]
同样问题 RN版本0.595

**Comment by superodin** [comment]
我是0.59.9，同样的错误，这个已经解决了吗？

**Comment by cicistream** [comment]
有解决办法嘛？

**Comment by cicistream** [comment]
> error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/sean/文档/project/Flavours_4.0/node_modules/teaset/components/ListRow/node_modules/teaset/icons'

解决办法是什么鸭

**Comment by vurtnec** [comment]
有人解决了么

**Comment by housenkui** [comment]
没有给解决方法，怎么就关上了 喔喔喔👀

**Comment by housenkui** [comment]
@XHTeng  重启电脑 不能解决，我是0.59.9.

**Comment by TaumuLu** [comment]
我升级到了最新版解决了
"react-native": "0.59.10"
"teaset": "^0.7.1"

**Comment by dingyongg** [comment]
同样的问题， 这问题结局了吗

**Comment by dingyongg** [comment]
> 重启电脑就好了

尽灌水...
