### ISSUE TITLE
Overlay.PullView刷新页面问题

### ISSUE THREAD

**Issue by China-Robin** [rilyu/teaset#339]
当调用Overlay.show(overlayView);方法的时候，页面会被重新渲染，换成PoPView也会有这个情况

![未命名](https://user-images.githubusercontent.com/13116572/54101336-0ec42300-43fe-11e9-8f5e-711e20e6a555.gif)

**Comment by China-Robin** [comment]
找到原因了，是因为我的触发按钮使用的是TouchableHighlight，换成TouchableOpacity就好了，至于为什么？谁知道呢，被坑死~~

**Comment by China-Robin** [comment]
close #339

**Comment by China-Robin** [comment]
找到原因了，是因为我的触发按钮使用的是TouchableHighlight，换成TouchableOpacity就好了，至于为什么？谁知道呢，被坑死~~额，顺便帮忙关闭一下这个issue，我不会！！！

**Comment by handsameliu** [comment]
我说怎么其他界面没事，，，我一度开始调试源代码了，帮了我大忙，，
