### ISSUE TITLE
react 16.0.0-alpha.13 去除了 React.PropTypes 希望作者下次更新为prop-types

### ISSUE THREAD

**Issue by IamMonkey** [rilyu/teaset#34]
Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

**Comment by rilyu** [comment]
0.2.7 版已经修复这个问题，由于使用了 react-native-deprecated-custom-components ，似乎 Facebook 已经不再维护， 修复此问题的 Pull request 没有合并，因此运行时还会有提示，待 react-native-deprecated-custom-components 修复后将完全修复
