### ISSUE TITLE
`npm install`安装失败!!!!!

### ISSUE THREAD

**Issue by hms111111** [rilyu/teaset#349]
D:\hms\react native test1\teaset-master\example>npm install
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/facebookarchive/react-native-custom-components.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-04-09T08_22_59_874Z-debug.log

**Comment by jim888666** [comment]
兄弟你解决了吗？？我也是这样的报错

**Comment by JackSayHello** [comment]
要安装git，环境变量Path加git路径
验证git安装成功：cmd执行
```
git --version
```
显示出版本号表示成功（执行npm install 的地方也要执行成功，不成功就否则重启cmd或ide或系统）

**Comment by CodeRabbitYu** [comment]
可以试试yarn。。。 安装不上teaset，和这个库基本没有关系

**Comment by ytt123** [comment]
下午用yarn add teaset 安装上了

**Comment by taoqf** [comment]
> 可以试试yarn。。。 安装不上teaset，和这个库基本没有关系

绝对有关系,难道非得说是工非干的事吗?package.json中依赖了github上的东西,而那个地址在我们局域网是下载不了的.

**Comment by rilyu** [comment]
最新版已把该依赖包发布到 npm ，不再依赖 github https://github.com/rilyu/teaset/commit/645a1dbcd6621a6624c4dbc2176ed87469323010
