### ISSUE TITLE
Select 有办法在modal上显示吗

### ISSUE THREAD

**Issue by s349856186** [rilyu/teaset#358]
Modal 弹框上面有个按钮，点击按钮需要展示一个选择列表，这个Select有机会在modal上显示吗

**Comment by zsswlr** [comment]
model 里面走动态子组件


------------------ 原始邮件 ------------------
发件人: "Jack"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 下午3:34
收件人: "rilyu/teaset"<teaset@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [rilyu/teaset] Select 有办法在modal上显示吗 (#358)




Modal 弹框上面有个按钮，点击按钮需要展示一个选择列表，这个Select有机会在modal上显示吗

**Comment by s349856186** [comment]
@zsswlr 如何在modal上动态添加子组件，没有找到资料，有推荐文档吗，谢谢

**Comment by zsswlr** [comment]
动态组件

发自我的 iPhone

**Comment by s349856186** [comment]
还是不明白如何操作，谢谢了
