### ISSUE TITLE
如何取得<TabView />的上中下三个部分的高度？

### ISSUE THREAD

**Issue by my4piano** [rilyu/teaset#36]
如何取得<TabView />的上（顶部导航栏）中（内容页）下（底部导航栏）三个部分的高度？内容页我想放置一个地图view，但是地图view 的控件被 底部导航栏遮盖了

**Comment by rilyu** [comment]
顶部导航条高度是固定的，iOS 为 64，Android 为 44，这是依照原生系统的来设置的；
TabBar 的高度在 Theme 设置，默认为 49 ；
屏幕高度减去这两个高度就是中间内容区域的高度。

不建议自己计算这个高度，很麻烦，如屏幕翻转还需要重新计算，建议使用 Flexbox 布局来实现， Teaset 几乎所有的组件都是使用 Flexbox 布局，如果你的页面是继承自 NavigationPage ，你只需要把你的 MapView 的 style 属性加上 {flex: 1} 即可，如：
```
  renderPage() {
    return (
      <MapView style={{flex: 1}}>
        ...
      </MapView>
    );
  }
```

**Comment by siroer** [comment]
你的建议很好，已解决：）
