### ISSUE TITLE
Projector 中child生命周期异常

### ISSUE THREAD

**Issue by s949492225** [rilyu/teaset#360]
用Projector做tab切换页面,
不明白为什么tab切换后Projector中页面的状态还在,
当tab切换后Projector中是根据index判断是渲染child还是null,
当原来渲染child,现在渲染null的话,那原来的child不应该被销毁掉了吗,为什么再切换回来那个child的状态还会保留,我说的状态是指ScrollView划到中间,tab切换回来还在中间这种状态,按照预期应该是组件切走时被销毁,切回来再重新创建,希望作者能够解惑,万分感谢

**Comment by wanglaohushiwo** [comment]
> 用Projector做tab切换页面,
> 不明白为什么tab切换后Projector中页面的状态还在,
> 当tab切换后Projector中是根据index判断是渲染child还是null,
> 当原来渲染child,现在渲染null的话,那原来的child不应该被销毁掉了吗,为什么再切换回来那个child的状态还会保留,我说的状态是指ScrollView划到中间,tab切换回来还在中间这种状态,按照预期应该是组件切走时被销毁,切回来再重新创建,希望作者能够解惑,万分感谢

和Projector的实现有关系，Projector是通过控制item的Opacity来实现页面的可见和不可见的，相当于把页面给缓存了。
