### ISSUE TITLE
Document in English

### ISSUE THREAD

**Issue by emersonlaurentino** [rilyu/teaset#37]
[**Hey, im translating the documents to english.**](https://github.com/rilyu/teaset/blob/master/docs/cn/README.md#文档)

Here is the project:
https://github.com/emersonlaurentino/teaset/projects/1

**Comment by rilyu** [comment]
OK, I will add the link to README.md

**Comment by emersonlaurentino** [comment]
ow, okay.

when im done, I'll send you a pull request...
