### ISSUE TITLE
升级最新版本，使用redux无法显示overlay组件

### ISSUE THREAD

**Issue by SeptSky** [rilyu/teaset#371]
升级teaset（0.6.3）最新版本（RN为0.60.4），基于overlay的组件都无法显示了，按照帮助的提示：
`
container => () => <Provider store={store}><TopView>{container}</TopView></Provider>
`

上面的代码有些不明白如何使用，是下面的使用方式吗？
` 

     <Provider store={store}>

        <TopView>

          <TeaNavigator rootView={<HomeRouter />} />

        </TopView>

      </Provider>
`
其中HomeRouter是自定义的首页组件。
调试运行后，依然无法显示overlay组件，请教是哪里的问题？
谢谢！

**Comment by danna88** [comment]
请问怎么解决的呢？

**Comment by isllyend** [comment]
0.61.5遇到同样问题  加入<TopView>无效果
