### ISSUE TITLE
Carousel 下标和视图不匹配

### ISSUE THREAD

**Issue by stempest0925** [rilyu/teaset#381]
概率性的，会出现页面变成最后一个下标，但是下标还是第一个。
设置startIndex无效，在mount中scrollToPage也无效

**Comment by yangfanyu** [comment]
我是通过自定义导航按钮解决的：
<SegmentedView.Sheet
                        title={
                            <Label type='title' size='lg' style={{color: this.state.activeIndex === 0 ? Theme.sbBtnActiveTitleColor : Theme.sbBtnTitleColor}}>发现</Label>
                        }>
                        <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
                            <Label type='detail' size='xl' text='发现'/>
                        </View>
</SegmentedView.Sheet>

<SegmentedView.Sheet
                        title={
                            <Label type='title' size='lg' style={{color: this.state.activeIndex === 1 ? Theme.sbBtnActiveTitleColor : Theme.sbBtnTitleColor}}>新品</Label>
                        }>
                        <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
                            <Label type='detail' size='xl' text='新品'/>
                        </View>
</SegmentedView.Sheet>

**Comment by GuoJiKaiHehe** [comment]
这个好像是最新版本的问题。我用之前的版本没有这个问题

**Comment by stempest0925** [comment]
陈旧的问题
