### ISSUE TITLE
Something wrong with SearchInput's value

### ISSUE THREAD

**Issue by TGSoftware** [rilyu/teaset#39]
Hi, cool library.
But I found something wrong when I used SearchInput in Overlay.
**Problem is the input area will be cleared after editing**.
So I change the source of SearchInput line `if (value === undefined) value = this.state.value;` to `value = this.state.value;`  in method `render()`.
Dont know if this is right. Hope for your fix.

**Comment by rilyu** [comment]
The value prop of SearchInput like [TextInput](https://facebook.github.io/react-native/docs/textinput.html#value), if you do not want to deal with listening to onChangeText event and updating the value prop to keep the controlled state in sync, you can use [defaultValue](https://facebook.github.io/react-native/docs/textinput.html#defaultvalue).
