### ISSUE TITLE
yarn add teaset failed

### ISSUE THREAD

**Issue by RathaKrishna** [rilyu/teaset#391]
I facing this error from yersterday, If i use

> npm install teaset

then facing problem on pod install

error An unexpected error occurred: "https://raw.githubusercontent.com/rilyu/react-native-custom-components/27074674fdfd223c4d350fc9ba4bec0ed724767e/package.json: connect ECONNREFUSED 31.13.85.8:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mac/Desktop/ARPA_React/YunDaTianXia/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by rilyu** [comment]
Please try the latest version https://github.com/rilyu/teaset/commit/645a1dbcd6621a6624c4dbc2176ed87469323010
