### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by eduhds** [rilyu/teaset#408]
I have this issue with Teaset after update RN, and only work when I comment export and import lines from some components as Theme, Label, Button, and others. In node_modules/teaset/index.js file.

"react": "16.11.0",
"react-native": "0.62.0-rc.1",
"teaset": "^0.7.1"

![Screenshot_2020-02-10-14-56-19 1](https://user-images.githubusercontent.com/27029124/74744738-81aa6080-5241-11ea-8f9b-8b5b2462320d.png)

**Comment by orzhtml** [comment]
+1

**Comment by excitedcat** [comment]
+1

**Comment by excitedcat** [comment]
![image](https://user-images.githubusercontent.com/8253512/77754741-e5a51d80-7066-11ea-83ed-80316efc26f0.png)

**Comment by zgjYswor** [comment]
+1

**Comment by bombomzhou** [comment]
+1

**Comment by excitedcat** [comment]
所有 `extends TouchableOpacity` 的地方可能都要改

**Comment by JonsonHI** [comment]
+1

**Comment by excitedcat** [comment]
@Henriqueedu @JonsonHI @rilyu 0.7.4 版本好像修复了这些问题，大家测试一下

**Comment by rilyu** [comment]
问题已修复，0.7.4 需要 rn0.62.0以上，早期版本请使用 teaset@0.7.1

**Comment by Henriqueedu** [comment]
> 
> 
> 问题已修复，0.7.4 需要 rn0.62.0以上，早期版本请使用 teaset@0.7.1

It's works fine. Thanks!

**Comment by songxiaoliang** [comment]
如果依赖库很多，一一排查有点难，有没有更好的方法去解决这个问题呢？
