### ISSUE TITLE
SegmentedView 使用这个组件创建3个页面,是一次性加载完成的吗?

### ISSUE THREAD

**Issue by SurpassRabbit** [rilyu/teaset#42]
1.要实现类似`react-native-scrollable-tab-view`这个库的样式, 使用`SegmentedView`之后,发现里面的子页面是一次性加载完成的. 能不能实现`react-native-scrollable-tab-view`那样, 按需加载呢?
如果是一次性加载完的, 如果页面都一样,输入请求就是一次性请求完了..
2.还有`SegmentedView` 里面只提供了`onChange`这样的属性,如果我想在滚动的时候,让底部的滚动条颜色改变, 展示上会有问题.

**Comment by rilyu** [comment]
1 type = 'projector' 时，首次切换到该页面时加载；type = 'carousel' 时，一次加载全部页面
2 如果你需要滚动事件，SegmentedView 使用 Carousel 组件实现滚动页面，Carousel 支持 ScrollView 的所有属性与事件，你可以参照 SegmentedView 或 SegmentedBarExample 自行实现 SegmentedView 同样的功能，可以自行监听 Carousel.onScroll 事件，代码也比较简单

**Comment by SurpassRabbit** [comment]
不能按需 加载吗?  一次性加载,对性能影响太高了...  如果要是做新闻那种效果. 那一次性加载十几个会崩溃的

**Comment by rilyu** [comment]
type = 'carousel' 时使用 Carousel 组件，目前暂时不支持自动按需加载，改动的影响太大了，如需要你可以自行实现，例：
```
  constructor(props) {
    super(props);
    this.state = {
      activeIndex: 0,
      loads: [true, false, false],
    }
  }

  renderPage() {
    let {loads} = this.state;
    return (
      <View style={{flex: 1}}>
        <SegmentedView
          style={{flex: 1}}
          onChange={index => {
            loads[index] = true;
            this.setState({activeIndex: index, loads});
          }}
        >
          <SegmentedView.Sheet title='0'>
            {loads[0] ? <YourPage0 /> : <View />}
          </SegmentedView.Sheet>
          <SegmentedView.Sheet title='1'>
            {loads[1] ? <YourPage0 /> : <View />}
          </SegmentedView.Sheet>
          <SegmentedView.Sheet title='2'>
            {loads[2] ? <YourPage0 /> : <View />}
          </SegmentedView.Sheet>
        </SegmentedView>
      </View>
    );
  }
```

**Comment by SurpassRabbit** [comment]
好的 。谢谢啦。
