### ISSUE TITLE
对于标签页的Custom,Android中间按钮无法突出吗?

### ISSUE THREAD

**Issue by pheromone** [rilyu/teaset#44]
打扰一下,对于标签页的Custom,Android中间按钮无法突出吗?如下图所示:
![2017-08-24 10 38 34](https://user-images.githubusercontent.com/14305431/29646863-70e8c930-88b8-11e7-8163-bad1b0363e17.png)

**Comment by rilyu** [comment]
抱歉，之前没考虑到 Android 不支持 overflow , 所以这个功能 暂时无法在 Android 下工作，react native 可能在今年内 Android 会支持 overflow ，参见：https://github.com/facebook/react-native/issues/6802#issuecomment-299945894

谢谢提交问题，我已修改 DrawerExample 在 Android 下能正常工作了，但

**Comment by pheromone** [comment]
谢谢
