### ISSUE TITLE
将本页数据 this.navigator.pop() 返回给上一页，teaset 有没有什么实现方法？

### ISSUE THREAD

**Issue by siroer** [rilyu/teaset#45]
RT

**Comment by rilyu** [comment]
Teaset 没提供这样的方法，一般的做法是在当前页面组件加一个事件函数，由调用这传入，然后当前页面在调用 this.navigator.pop() 前回调这个事件函数传入需要返回上一级页面的数据；如果是跨级传递，可以考虑使用Redux或其它数据流框架，也可以采用 DeviceEventEmitter 事件发送-接收机制自行实现。
