### ISSUE TITLE
REPORT:A NEW BUG WITH SegmentedView.Sheet 

### ISSUE THREAD

**Issue by MicroKibaco** [rilyu/teaset#46]
## I like the Lib,and now I have some question?

1. Why don't you use navagation to replace the navagator?

2. why don't you use Flux and Redux

3.  now I find a bug ,when i used SegmentedView.Sheet's title property ,I find if the page status has changed,This component will be rendered

> for example ,if i used TextInput or your InputRow,SegmentedView.Sheet's title property it will grab the spotlight,i have no idea to control the TextInput content change caused Title state change

4. and SegmentedView.Sheet need to resolve pull-down refresh the event of conflict

Finally, I hope you can add me QQ**56927299** communicate RN together

**Comment by rilyu** [comment]
1. I will use Navigation to replace the Navigator, but not now
2. I need to control everything when developing, and Redux has too many restrictions
3. Please provide the code for me to check the cause of this problem
4. There is no good idea to achieve this function

thx
