### ISSUE TITLE
运行demo的时候发现切换页面有点慢

### ISSUE THREAD

**Issue by Chaunjie** [rilyu/teaset#48]
是打包jsbundle之后真机运行(iphone 5s)切换页面有点卡，模拟器运行切换不会，不知有没有好的解决方案？ @rilyu

**Comment by rilyu** [comment]
iphone 5s 性能比较差，跑debug会有卡顿，你在 xcode 使用 release scheme 方式运行，并且关掉 debug ，这样就会很流畅了，我在 iphone 4s 上测试过都挺好的，瞬间切换

**Comment by Chaunjie** [comment]
好的谢谢
