### ISSUE TITLE
[Menu] How to change the menuItem color and backgroundColor 

### ISSUE THREAD

**Issue by ElonXun** [rilyu/teaset#5]
[Menu] How to change the menuItem color and backgroundColor ??

**Comment by rilyu** [comment]
The simple way is to set the Theme object properties:
```
Theme.set({
  menuColor: 'rgba(90, 74, 124, 0.9)',
  menuShadowColor: '#333',
  menuItemColor: 'rgba(0, 0, 0, 0)',
  menuItemTitleColor: '#c1c2cc',
  menuItemSeparatorColor: '#292f4f',
  menuItemIconColor: '#c1c2cc',
});
```
Theme object default properties in [ThemeDefault.js](/themes/ThemeDefault.js)
You only need to set it once when App starts running

**Comment by ElonXun** [comment]
Thanks .
