### ISSUE TITLE
Select to accept a function for rendering the items.

### ISSUE THREAD

**Issue by c-a-d-a** [rilyu/teaset#51]
First of all, I love your work. It is really great. But I have one feature request.

It would be nice if Select component could have a prop for rendering the items and selected item. e.g.

`renderItem(item, index) {
  return (<Text>{item}</Text>);
}`

This is to replace the getItemText prop.
This open up possibility to make a picker for Images and others.
I saw `PopoverPickerItem` already supports this.

**Comment by rilyu** [comment]
Supported, view SelectExample.js for example https://github.com/rilyu/teaset/commit/8c10f86c61d0aa24d3d3e74e40ef6875e0310980

**Comment by c-a-d-a** [comment]
Awesome. I have checked it out. It works. Thanks a lot man!
