### ISSUE TITLE
AlbumView.js  onChange触发时使用了未定义的index

### ISSUE THREAD

**Issue by z372183629** [rilyu/teaset#52]
版本0.3.2
AlbumView.js 176行
can't find variable : index

**Comment by z372183629** [comment]
相册组件很好用，有些小细节我觉得可以优化下，比如 单击事件和长按事件表现得并不灵敏，我猜应该是稍微有一点移动都会被判定为别的手势。
感谢开源，一直在使用teaset的组件，省了很多事

**Comment by rilyu** [comment]
谢谢报告问题，相册组件正在重构中，新版本页内容将支持 React 组件而不仅仅是图片，同时加载图片后会缓存起来，避免比较大的网络图片有加载时延，你提的这些问题将被同时考虑进去

**Comment by rilyu** [comment]
已修正
