### ISSUE TITLE
TabView.Sheet的activeIcon始终都是蓝色而不是图标本来的颜色

### ISSUE THREAD

**Issue by yongyuanfan** [rilyu/teaset#53]
请问如何显示图标本来的颜色呢？

**Comment by rilyu** [comment]
TabView.Sheet 的 activeIcon 属性默认使用 Theme.tvBarBtnIconActiveTintColor 作为 tintColor，有两种方法实现使用图标原来的颜色，一是在代码入口处删除 Theme.tvBarBtnIconActiveTintColor 设置，影响所有 TabView.Sheet：
```javascript
Theme.set({tvBarBtnIconActiveTintColor: undefined});
```

二是自行渲染 activeIcon 组件：
```javascript
        <TabView.Sheet
          title='Home'
          icon={require('../icons/home.png')}
          activeIcon={<Image style={{height: 20, width: 20}} source={require('../icons/home_active.png')} />}
        >
```

**Comment by yongyuanfan** [comment]
感谢作者大神的回答，第一种方案完美解决了我的问题。
第二种方案的缺陷就是不能同时修改title的颜色。
感谢作者为我们提供这样好的作品，我这样刚接触react native的新人用起来也很简单。

**Comment by huming-china** [comment]
@yongyuanfan   请问你是怎么设置title的颜色的
