### ISSUE TITLE
請問有沒辦法為NavigationBar添加背景圖？

### ISSUE THREAD

**Issue by winsonet** [rilyu/teaset#54]
我嘗試過直接將一個 Image 包住整個 NavigationBar，但發現這樣整個位置都會亂了，完全沒法用，不知有什麼其他辦法可做到嗎？非常感謝!!

**Comment by winsonet** [comment]
嗯，雖然不太好，不過我最終還是通過直接改寫 NavigationBar 控件實現了 :)

**Comment by rilyu** [comment]
你在传入的 title 属性返回一个绝对定位且占满整个容器空间的 View ，View 里再放 Image 就行了。
例：
```javascript
  renderNavigationTitle() {
    return (
      <View style={{position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center'}}>
        <Image style={{position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, width: undefined, height: undefined}} resizeMode='cover' source={require('../images/teaset2.jpg')} />
        <Text style={{backgroundColor: 'rgba(0, 0, 0, 0)', color: '#fff', fontSize: 17}}>Image navigation bar</Text>
      </View>
    );
  }
```

**Comment by winsonet** [comment]
嗯，我試了你的方法，但背景圖只能加到 title 的範圍，運行你的代碼後就是以下的效果：

![20170911_navbar_01](https://user-images.githubusercontent.com/1869995/30281751-d53e9cca-9745-11e7-9a6b-66f758e931dc.jpg)

但其實我想要的是以下的效果：

![20170911_navbar_02](https://user-images.githubusercontent.com/1869995/30282049-b672911a-9746-11e7-94a2-12751484a5e0.jpg)


我現在的做法是為 NavigationBar 控件添加了一個 backgroundImage 的屬性，然後可以直接設置，其實就是在源碼裏添加了一個 Image，其實我建議如果可以的話，也希望你可以在下一個版本裏添加上這個屬性，而且我還添加了一個 height 的屬性，因為我還需要自行設置整個 NavigationBar 的高度，當然如果你能提供更好的方法而不需要修改源碼的話，那就更好啦，謝謝！ :)

**Comment by rilyu** [comment]
好提议，我考虑一下在下一版本支持背景图。
另外，只需要在 NavigationBar.style 中指定 height 属性就可以设置高度了， Teaset 遵循 React 的约定，组件样式均在 style 中设置

**Comment by winsonet** [comment]
哦，好的，關於高度的設置，我回去再試試，當時好像直接設置有點問題，謝謝啦！！
