### ISSUE TITLE
關於使用react-native-vector-icons作為TabView icon的問題

### ISSUE THREAD

**Issue by winsonet** [rilyu/teaset#57]
我發現如果使用 [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) 作為TabView icon的話，其位置會有問題，總是高出了一部分，如下圖：

![tab_issue1](https://user-images.githubusercontent.com/1869995/30282676-8e102b40-9748-11e7-8d31-eb5ed96b18e9.jpg)

但我直接修改 TabButton.js 源碼後，為其添加了固定的高度，問題就可以解決了，如下代碼：

```
iconContainerStyle = [{
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      height:30  //此為新加代碼
    }].concat(iconContainerStyle);
```

添加後效果如下：

![tab_issue2](https://user-images.githubusercontent.com/1869995/30282749-c530edb2-9748-11e7-9b44-bf5ef00db573.jpg)

之所以在此提出，是希望你也許會有更好的解決辦法，不需要我直接修改框架源碼，而且我也不確定如果我這樣直接改，會不會對其他地方會產生影響（如萬一要改變 TabView 的高度）？ 

當然，我提出來的另一個原因，是因為我感覺你這套框架實在很吸引我(在此前我已嘗試過好幾個流行的RN UI框架，但都感覺不太好用)，特別是整個編程的思路都很好，其實我也是剛接觸 RN，從你這框架裏我學到不少東西，所以也希望你這個能越做越好，謝謝啦 !

**Comment by rilyu** [comment]
新增大按钮支持后我没有作太多的兼容性测试，可能会存在一些问题，但解决这个问题不需要直接修改 Teaset 源代码的，只需要在 TabSheet.iconContainerStyle 传入你需要增加的属性即可，例如
```javascript
  <TabView.Sheet
    title='Home'
    icon={require('../icons/home.png')}
    activeIcon={require('../icons/home_active.png')}
    iconContainerStyle={{height:30}}
  >
```
可以暂时这么解决，有时间我再测试一下 react-native-vector-icons

提示：指定高度后在 Android 下大按钮可能显示不全，可能需要单独指定大按钮的高度

**Comment by winsonet** [comment]
哦，好的，謝謝啦~~
