### ISSUE TITLE
可以出拍照片和视频的组件么？

### ISSUE THREAD

**Issue by siroer** [rilyu/teaset#58]

**Comment by rilyu** [comment]
目前照片、视频需要原生代码才能实现，Teaset 的目标是使用纯 ES6 来实现，目前暂时没有写原生代码的计划。推荐使用以下组件：
[react-native-image-picker](https://github.com/react-community/react-native-image-picker): 高度封装，简单易用，但在部分国产 Android 手机下易崩溃，如: vivo oppo huawei 等品牌部分机型
[react-native-camera](https://github.com/lwansbrough/react-native-camera): 给你直接访问照相机的能力，需要自己编写 UI ，自由度高
