### ISSUE TITLE
ModalIndicator.show() return undefined

### ISSUE THREAD

**Issue by Lihyrs** [rilyu/teaset#59]
[但文档上写有返回值](https://github.com/rilyu/teaset/blob/master/docs/cn/ModalIndicator.md)

**Comment by rilyu** [comment]
感谢指出问题，文档写错了，同一时刻只能显示一个模态指示器，不需要返回值的，已修正：https://github.com/rilyu/teaset/commit/1fd939feb79af212917108f593a01d9df4b5725d

**Comment by Lihyrs** [comment]
非常好的库,感谢作者
