### ISSUE TITLE
ModalIndicator多次调用hide方法不生效

### ISSUE THREAD

**Issue by Chaunjie** [rilyu/teaset#63]
fetchGet(data, callback){
        ModalIndicator.show(`正在加载...`);
        const paramsStr = this.getParamsStr(data.params);
        const url = Services.Api + data.interFun + '?' + paramsStr;
        this.getHttpRequest(url, function (res) {
            ModalIndicator.hide()
            callback && callback(res);
        });
    }

我是做了这么一个共有请求方法，出现了一个问题，当一个页面初始化三个接口的时候ModalIndicator就不会消失 @rilyu 有好的解决方案吗？

**Comment by xzgilhm** [comment]
请问您当时发现问题的原因了么? @Chaunjie

**Comment by Chaunjie** [comment]
@xzgilhm 调用show之前先执行下hide吧

**Comment by xzgilhm** [comment]
> @xzgilhm 调用show之前先执行下hide吧

谢谢，应该可以了。
