### ISSUE TITLE
tabview设置activeIndex属性后点击其它tab不能切换

### ISSUE THREAD

**Issue by shz8** [rilyu/teaset#64]
需要将teaset\components\TabView\TabView.js文件中
  get activeIndex() {
    let activeIndex = this.props.activeIndex;
    if (activeIndex || activeIndex === 0) return activeIndex;
    else return this.state.activeIndex;
  }
改为
  get activeIndex() {
    let activeIndex = this.props.activeIndex;
    if (this.state.activeIndex || this.state.activeIndex === 0) return this.state.activeIndex;
    else return activeIndex;
  }

**Comment by rilyu** [comment]
这么修改后就没办法在外部修改当前活动页面了，不能这么改的，props 优先于 state，如果传入 activeIndex 属性，则需要监听 onChange 事件自行维护 activeIndex 状态，这是符合 React Native 习惯的。
最初考虑到尽可能简单，所以删掉只使用一次的 defaultActiveIndex 属性了，后面再看看是否加上。
