### ISSUE TITLE
Overlay.PullView 可以显示一个超出的view吗

### ISSUE THREAD

**Issue by Josin22** [rilyu/teaset#65]
![wx20170925-101707](https://user-images.githubusercontent.com/9657587/30789819-bb187fe2-a1da-11e7-8a86-5689709966ca.png)
如图,image超出部分可以显示吗

**Comment by rilyu** [comment]
可以的，实现方法参考 [DrawerExample.js](https://github.com/rilyu/teaset/blob/master/example/views/DrawerExample.js)

**Comment by rilyu** [comment]
iOS 简单地使用 overflow: 'visible' 就可以了，但 Android 不支持 overflow，因此例子中使用了变通方法
