### ISSUE TITLE
why does not the drawer support a react component?

### ISSUE THREAD

**Issue by CesyZhao** [rilyu/teaset#66]

**Comment by rilyu** [comment]
Drawer fully supports the react components, see [DrawerExample.js](https://github.com/rilyu/teaset/blob/master/example/views/DrawerExample.js)

**Comment by CesyZhao** [comment]
but when i open a component imported from another file , the drawer  just didn't show up. Am i using it in the wrong way?

**Comment by rilyu** [comment]
Try to change the component into a View for test, don't forget to set the height or / and width value

**Comment by CesyZhao** [comment]
thank you for you suggestion and it was cause by i forgot to set the width property. really appreciate your work.
