### ISSUE TITLE
react新手，试图把teaset装到已有react app文件包中，总是装不成功

### ISSUE THREAD

**Issue by Veronica1026** [rilyu/teaset#67]
我有一个已经写了login page 的app项目叫做group，想要安装teaset，用这里的一些组件写其他页面但是命令行试图安装teaset的时候总是不成功。他说某个文件已存在，应该删掉再装，但是删掉，报的错还是一样的，it学生一枚，没什么react经验，请问这是怎么回事啊？ 我后面试图新建一个文件，但是安装teaset以后新文件就运行不了，simulator报错说没有index.js文件。但是我是用react-native init project 新建的，而且安装teaset以前也可以正常跑，安装以后整个project久跑不了了，请问这是发生了什么呀？

![111](https://user-images.githubusercontent.com/23331311/31221366-f18b67d2-aa0a-11e7-8d10-d804b531654a.jpeg)

**Comment by rilyu** [comment]
删除 node_modules 目录并重新运行 npm install 试试
注：node_modules 下存放的是 npm 安装的模块，必须遵守的约定是你不能修改次目录下的任何文件，且运行 npm 安装模块时有加 --save 开关，否则不能使用上述方法
