### ISSUE TITLE
teaset 现在能支持 rn 最高版本 是多少？

### ISSUE THREAD

**Issue by my4piano** [rilyu/teaset#68]
teaset 现在能支持 rn 最高版本 是多少？

**Comment by rilyu** [comment]
teaset开发环境是0.47.1，在0.48.3版本下测试正常，最新版本应该都支持的，如有问题请贴出错误信息

**Comment by my4piano** [comment]
0.48.3、0.48.3 Example  npm install 后也报错  

 
10-07 14:26:41.654 10298 10336 E ReactNativeJS: undefined is not an object (evaluating 'ReactInternals.R
eactCurrentOwner')
10-07 14:26:41.700 10298 10336 E ReactNativeJS: Module AppRegistry is not a registered callable module (
calling runApplication)
![tim 20171007223014](https://user-images.githubusercontent.com/17940455/31308777-1c83c36c-abaf-11e7-8eea-37070c8c375f.png)

**Comment by rilyu** [comment]
可能和 react native 某些不兼容升级有关，我使用 react native 0.49.2 最新版本重建了 example 工程并发布新版本，在 android 和 ios 下测试均正常

**Comment by my4piano** [comment]
0.49.2 确实没问题，结帖
