### ISSUE TITLE
Slow on Android?

### ISSUE THREAD

**Issue by JCKodel** [rilyu/teaset#7]
In Example project, each "click" takes about 5 seconds to be processed (navigation from home to some option), and Overlay animations are very slow.

Tested on a low-end device (Moto G XT 1033) and in a mid-end device (Asus ZenFone 2 Selfie).

**Comment by rilyu** [comment]
When React Native App is running on debug mode on the device, it may be very slow, which may be caused by the running environment, such as Remote Debug, etc. You can try to turn off Remote Debug or package for Release apk.
