### ISSUE TITLE
在浮层中使用Checkbox无法更新状态

### ISSUE THREAD

**Issue by zhuanglong** [rilyu/teaset#71]
![baidushurufa_2017-10-11_12-45-2](https://user-images.githubusercontent.com/19422011/31422687-0aae3642-ae82-11e7-9d7f-301574d1f02b.png)

点击Checkbox无反应，但onChange是有更新的

**Comment by rilyu** [comment]
你确认一下是否传入了 checked 属性，如有传入 checked 则需要自行维护 checked 状态，例如：
```javascript
<Checkbox
  checked={this.state.checked}
  onChange={value => this.setState({checked: value})}
  />
```

**Comment by zhuanglong** [comment]
@rilyu 貌似用TopView实现的浮层不能更新状态

**Comment by rilyu** [comment]
晚点我再测一下，rn 升级到 0.49 后改动很大，估计需要些时间了

**Comment by rilyu** [comment]
测试了一下，原因应该是你在当前页面维护了浮层内 Checkbox 的 checked 状态，这样是不行的，浮层并不属于当前页面的子组件，当前页面改变状态并不会使得浮层刷新，这种情况下应该把浮层内容封装为一个组件，然后在这个组件内维护状态。
我修改了一下 Checkbox 代码，你使用 defaultChecked 来代替 checked 就可以在浮层中使用了，但这只是解决 Checkbox 问题，对于其它需要维护状态的组件还是存在类似情况的（如 Input），建议按前述方案处理。

**Comment by zhuanglong** [comment]
@rilyu 谢谢
