### ISSUE TITLE
PopoverPickerView.Item这个应该怎么用

### ISSUE THREAD

**Issue by SurpassRabbit** [rilyu/teaset#74]
PopoverPickerView 我要自定义没给Item的背景色，默认的是白色的，我不知道怎么使用这个属性

**Comment by rilyu** [comment]
如每个 Item 的背景色都是一致的，可通过修改 Theme.poppItemColor 来实现
```javascript
Theme.set({poppItemColor: '#fee'});
```
如果要完全自定义每个 Item ，则需要在 PopoverPickerView.getItemText 属性返回一个 React Native 元素，这个元素会作为 Item 渲染

**Comment by SurpassRabbit** [comment]
我想知道PopoverPickerView.getItemText  这个方法应该怎么才能调用。  您的Demo上，我全都看了，也没看到自定义这个的

**Comment by rilyu** [comment]
类似这样
```javascript
PopoverPicker.show(
  {x, y, width, height},
  this.items,
  this.state.selectedIndex,
  (item, index) => this.setState({selectedIndex: index}),
  {getItemText: (item, index) => <View style={{backgroundColor: '#f00'}}><Text>{item}</Text></View>}
);
```

目前暂时只能修改 Item 容器内元素的背景色， 没有提供 Item.style 的修改方法，我看看怎么支持比较合适

**Comment by SurpassRabbit** [comment]
好的，十分感谢。

**Comment by SurpassRabbit** [comment]
大神，能留个QQ号吗? 或者加一下我 515236489，我想做个简单的脚手架，准备UI框架推荐用你这个。 http://www.jianshu.com/u/9895046b765d  这是我的简书。 希望可以收到回复，谢谢

**Comment by zhutousan20** [comment]
大神。我想问一下。弹出的打勾怎么去掉

**Comment by yuanxiaodong1** [comment]
大神，我想问一下，如何让它下移？弹出的样式
