### ISSUE TITLE
苹果8 Plus上wheel控件显示不正常

### ISSUE THREAD

**Issue by Mscynol** [rilyu/teaset#76]
有一条很明显的灰色带
![d578f87a-e667-4298-9375-0ada0e00bc42](https://user-images.githubusercontent.com/13941582/32031974-28cb043c-ba37-11e7-8b39-212713d6d8e6.png)

**Comment by Mscynol** [comment]
![d578f87a-e667-4298-9375-0ada0e00bc42](https://user-images.githubusercontent.com/13941582/32031959-0f130d32-ba37-11e7-9010-121984b6808e.png)

**Comment by rilyu** [comment]
已修复：https://github.com/rilyu/teaset/commit/7a2ca523a0ed0765468891b2ef132423619d0bc6

**Comment by Mscynol** [comment]
谢谢，建议添加hide（）时候的动画效果

**Comment by rilyu** [comment]
这个组件没有 hide 方法的
