### ISSUE TITLE
Wheel 问题

### ISSUE THREAD

**Issue by heart-bool** [rilyu/teaset#77]
我跟每一个Item 添加了点击事件，但是并没有被执行
         <Wheel
                            style={{width: width, height: WHEEL_BODY_HEIGHT - WHEEL_TITLE_HEIGHT}}
                            items={this.render_item(data)}
                            index={indexOf === -1 ? 0 : wheelIndex}
                            // defaultIndex={indexOf === -1 ? 0 : indexOf}
                            onChange={index => {
                                this.setState({wheelIndex: index})
                                bool ? this.setState({selectedBeiShuValue: data[index].toString()})
                                    : this.setState({selectedHeYueValue: data[index].toString()})
                            }}
                        />

render_item = (data) => {
        let arr = []
        data.map((item, index) => {
            arr.push(
                <TouchableOpacity
                    onPress={() => {
                        alert(this.state.wheelIndex)
                        this.setState({wheelIndex: index})
                    }}
                >
                    <Text style={{textAlign: 'center', width: width}}>{item}</Text>
                </TouchableOpacity>
            )
        })
        return arr
    }

**Comment by rilyu** [comment]
Wheel 的组件定义就是只能通过滚动来选择，选择项通过 translate 实现齿轮效果，没办法实现选择项点击的
