### ISSUE TITLE
关于组件样式

### ISSUE THREAD

**Issue by XinHuaLuFang** [rilyu/teaset#78]
我觉得组件的样式用assign比concat好些吧。
例如label中54行
```
style = [{
    backgroundColor: 'rgba(0, 0, 0, 0)',
    color: color,
    fontSize: fontSize,
    overflow: 'hidden',
}].concat(style);
```
用assign
```
style = Object.assign({
  backgroundColor: 'rgba(0, 0, 0, 0)',
  color: color,
  fontSize: fontSize,
  overflow: 'hidden'
}, style);
```

**Comment by XinHuaLuFang** [comment]
- 直截了当的声明样式比继承样式更好吧。
- 因为这里操作的是样式，所以应该不会有深拷贝、继承属性、不可枚举属性等问题。

**Comment by rilyu** [comment]
谢谢提出建议，使用 Object.assign 在 React 没有问题，但 React Native 组件的 style 是支持数组的，如果传入的是数组就不能用 Object.assign ， Teaset 的组件属性定义会尽可能保持与 React Native 一致，因此使用了 concat
