### ISSUE TITLE
TabView切换能Sheet能否重新渲染页面

### ISSUE THREAD

**Issue by shoutleafy** [rilyu/teaset#8]
目前的需求是一个TabView中包含了3个NavigationPage。
希望切换TabSheet的时候能够重新渲染页面。
componentWillMount只在第一次加载时触发，能否手动触发。
TabSheet类似于：
`<TabView style={{flex: 1}} type={this.state.type}>      
        <TabView.Sheet
          title='audit'
          icon={require('../assets/icons/png/audit.png')}
          activeIcon={require('../assets/icons/png/audit.png')}
        >
          <HomePage type={this.state.type} onChangeType={type => this.setState({type})} />
        </TabView.Sheet>
        <TabView.Sheet
          title='list'
          icon={require('../assets/icons/png/list.png')}
          activeIcon={require('../assets/icons/png/list.png')}
        >
          <HomePage type={this.state.type} onChangeType={type => this.setState({type})} />
        </TabView.Sheet>
        <TabView.Sheet
          title='cloud'
          icon={require('../assets/icons/png/cloud.png')}
          activeIcon={require('../assets/icons/png/cloud_active.png')}
        >
          <MePage type={this.state.type} onChangeType={type => this.setState({type})}/>
        </TabView.Sheet>
      </TabView>`

homePage中：
`componentWillMount() {
    console.log('componentWillMount');
    this.fetchData();
  }`

给您添麻烦了，先谢过！

**Comment by rilyu** [comment]
你是希望在 TabView 切换到 HomePage 时调用 HomePage 的 fetchData 刷新数据吧，可以类似这样
```
<TabView onChange={index => index == 0 && this.refs.home && this.refs.home.fetchData()}>
  <TabView.Sheet>
    < HomePage ref='home' />
  </TabView.Sheet>
</TabView>
```
