### ISSUE TITLE
paddingCorner 属性问题

### ISSUE THREAD

**Issue by heart-bool** [rilyu/teaset#81]
意思是 箭头和 align 位置的 距离吗？ 我设置了这个值但是没有反应啊

**Comment by heart-bool** [comment]
@rilyu

**Comment by rilyu** [comment]
有有效果的，是箭头元素与对齐角的距离，不是箭头尖端，你手动设置一下 height 和 width 就能看出来了
```javascript
<Popover style={styles.popoverStyle} arrow='leftBottom' paddingCorner={50}>
  <Label style={{height: 80}} text='Test' />
</Popover>
```

**Comment by heart-bool** [comment]
我现在用的popoverview 因为触发pop现实的地方在navigation的header静态方法里面 用不了ref 所以定义了一个隐藏的view在render里面 它们两个的位置是错开的 所以想移动箭头的位置 能实现吗？还有个问题 那个对其角到底是什么意思呢？

**Comment by rilyu** [comment]
不太清楚你的需求，如果设置了paddingCorner那就会按传入的值来渲染
arrow='leftBottom'，箭头在气泡左侧，向下对齐，leftBottom 左下角就是对齐角
