### ISSUE TITLE
在SegmentedView使用Input，然后输入东西就会爆这个错误。

### ISSUE THREAD

**Issue by SurpassRabbit** [rilyu/teaset#82]
<img width="498" alt="default" src="https://user-images.githubusercontent.com/10183022/32325662-d8f62b1a-c00a-11e7-8c8a-bc9b19974d81.png">

<img width="498" alt="default" src="https://user-images.githubusercontent.com/10183022/32325705-fd2e4148-c00a-11e7-8ff4-a2dae6adf6c3.png">

**Comment by rilyu** [comment]
已解决：https://github.com/rilyu/teaset/commit/41e8cae0d6c8eb93f1af9cb7a5b0fc1acca68c1e
