### ISSUE TITLE
static defaultProps

### ISSUE THREAD

**Issue by fujia666** [rilyu/teaset#83]
static defaultProps = {
    ...NavigationPage.defaultProps,
    title: 'Home',
    showBackButton: true,
  };
有两个问题请教,
1.返回上一页的Back可以改么?在哪里改?
2.想在这里加一个按钮可以么?怎么加?

**Comment by rilyu** [comment]
如全部的返回按钮修改标题，可通过修改 Theme 实现：
```javascript
Theme.set({
  backButtonTitle: '返回',
});
```
单独修改一个页面可重写该页面的 renderNavigationLeftView 函数，增加其它按钮请参阅 NavigationBarExample.js
