### ISSUE TITLE
Overlay.PullView在ios 弹出时，从导航栏上面弹出

### ISSUE THREAD

**Issue by qjloong** [rilyu/teaset#84]
怎么设置从导航栏下面弹出呢？

**Comment by qjloong** [comment]
@rilyu

**Comment by SurpassRabbit** [comment]
把react-navigation自带的导航隐藏掉，自己画一个View上去， 然后看Overlay的Demo，就够了

**Comment by rilyu** [comment]
Overlay 是顶层覆盖，没办法从导航栏下弹出，你需要自行实现，在当前页面容器建立一个绝对定位的覆盖层，自行实现从上往下弹出即可
