### ISSUE TITLE
建议开放官方网站

### ISSUE THREAD

**Issue by grapewheel** [rilyu/teaset#85]
wiki看得有点蛋痛

**Comment by rilyu** [comment]
目前没有精力做网站，阅读文档、参照例子应该就可以了，已经考虑组件设计尽可能简单

**Comment by grapewheel** [comment]
@rilyu 但使用者需要不断快速索引组件参数等，例如用docute做个wiki网站估计使用人数会提升很大，个人建议，不然我宁愿选择用antiMobile

**Comment by anchoretics** [comment]
@rilyu   是否可以考虑做的expo的放上去呢

**Comment by rilyu** [comment]
Teaset 是我在做去年做了几个 App 的过程中不断抽象和完善的结果，设计原则就是两点：纯 ES6、 极简接口，并不是专门投入去开发的一套 UI 框架，不过也是经过多个产品验证的，适用性还是比较强的，今年主要是做 React Native 升级版本适配、组件扩充和 bug 修复，没有精力去做更多的事情，或者明年会做吧。抱歉。

**Comment by pakyo-pan** [comment]
大神加油～ 支持！

**Comment by pakyo-pan** [comment]
@rilyu 大神加油～ 支持！

**Comment by grapewheel** [comment]
@rilyu 小弟膜拜，希望以后有机会能和大神共建React Native的国内知名UI框架和组件库

**Comment by rilyu** [comment]
欢迎🤝

**Comment by chen-wen** [comment]
给楼主点个赞

**Comment by chen-wen** [comment]
https://chen-wen.github.io/teaset/cn/

简单处理了一下添加了一个导航条 @rilyu 过目

**Comment by rilyu** [comment]
不错👍
不过页面没有兼容移动端，在手机查看被挡住大半，一般在移动端会把目录放在最后，或者不现实目录

**Comment by grapewheel** [comment]
@chen-wen 这个可以有，简单实用，PC浏览也够了
