### ISSUE TITLE
Overlay不能添加ScrollView?

### ISSUE THREAD

**Issue by xuechinahb** [rilyu/teaset#86]
想在Overlay.View或Overlay.PopoverView中添加ScrollView，但是却发现ScrollView无法滑动。已经手动设定了width和height。RN版本：0.44.3

**Comment by rilyu** [comment]
可以的，任何 React Native 组件均可使用，可能是某些属性设置问题导致不能滚动，比如这个：https://github.com/rilyu/teaset/issues/38
你可以先尝试在页面中测试你的代码，确认没有问题再放到 Overlay 中，或者贴代码出来看看

**Comment by xuechinahb** [comment]
```let overlayView = (
            <Overlay.PopoverView popoverStyle={styles.popoverStyle} fromBounds={fromBounds}
                                 direction={'down'} align={'center'} directionInsets={1}>
                <ScrollView>
                    <View>
                        {items}
                    </View>
                </ScrollView>  
            </Overlay.PopoverView>
        );   
Overlay.show(overlayView);

popoverStyle: {
        width: screenWidth - MARGIN * 2,
        padding: 5,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
    }

```
代码没问题。把上面ScrollView那段代码放到一个新页面中可以正常上下滚动。当用Overlay.View或Overlay.PopoverView包裹后，ScrollView不设置任何style，无法滚动，同时ScrollView中的内容溢出屏幕；如果ScrollView指定contentContainerStyle并设置确定的宽高，依然无法解决，同样无法滚动。在iOS上测试的。

**Comment by rilyu** [comment]
不应通过 contentContainerStyle 指定尺寸，在 style 指定即可

**Comment by xuechinahb** [comment]
都试过了，不行。现在发现，只有涉及Overlay的，ScrollView要么不能滑动，要么不显示。已放弃，使用新页面跳转。

**Comment by rilyu** [comment]
https://github.com/rilyu/teaset/issues/38 的代码我验证过，其实你这个问题我都不需要验证就能确定，因为 Teaset 的 Select 组件的选择框就是用 Overlay + ScrollView 来实现的，你看 Example 里的 Select 选择框能滑动吧？
