### ISSUE TITLE
Overlay 卡顿

### ISSUE THREAD

**Issue by xmqywx** [rilyu/teaset#87]
发现组件内容小的时候，弹出窗口流畅。当内容较大时，出现卡顿。
如嵌套组件，componentDidMount 时加载promise 请求 list。
如嵌套webview组件 ，componentDidMount 时发送数据较大的交互。 不知道怎么解决这一问题。

**Comment by rilyu** [comment]
通行的做法是等动画执行完毕后再执行比较耗时的操作，可以先测试在release版执行是否卡顿，有卡顿再改造，在 onAppearCompleted 事件调用加载数据函数即可
