### ISSUE TITLE
怎么在navigation上点击弹出menu

### ISSUE THREAD

**Issue by PeterLocas** [rilyu/teaset#88]
![image](https://user-images.githubusercontent.com/5467858/32875337-0e4f83cc-ca5d-11e7-8807-e7c2617423ba.png)

**Comment by rilyu** [comment]
方法是一样的，具体可参考 MenuExample.js ，在这个加号按钮的 onPress 事件弹出，要确保 加号按钮支持 measureInWindow 函数，否则你需要自己计算 fromBounds

**Comment by PeterLocas** [comment]
@rilyu 只能写按钮吗，不能用view?

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32875708-03768386-ca5f-11e7-8cde-695b5f1ea3fb.png)

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32875731-18a276fc-ca5f-11e7-95d8-6699f77c95ff.png)
不知道怎么传了

**Comment by rilyu** [comment]
可以，大部分 rn 组件都可以，自己封装的需要手工实现才行
你上面的代码，在加号那个 TouchableOpacity 加上 ref='add' 属性，然后把 MenuExample 的 show 函数移过来

**Comment by PeterLocas** [comment]
TouchableOpacity 不支持measureInWindow 
![image](https://user-images.githubusercontent.com/5467858/32876369-24c12994-ca62-11e7-9546-a343e56a5a17.png)

**Comment by rilyu** [comment]
不是，你这个是 this.refs['add'] 没取到值，不清楚你用的是什么导航条组件，不确定这个静态变量的内容是否在当前 this 对象内渲染，如果不是则取不到的
建议你用 Teaset 的 NavigationPage ，你这个页面熟练的话很快就能写好

**Comment by PeterLocas** [comment]
我用的是 react-navigation我明白你说的意思

**Comment by rilyu** [comment]
或者，你自己计算 fromBounds 就行了，不需要用 ref
```javascript
Menu.show({x, y, width, height}, items, {align});
```
自己计算上面的 {x, y, width, height} 的值

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32877365-cf860a9e-ca66-11e7-8250-176c9d2d7e29.png)
我是新手不懂你看看看

**Comment by rilyu** [comment]
不对，大致位置应该像下面代码这样，不对就再调一下数字
```javascript
import {Dimensions} from 'react-native';

let {width} = Dimensions.get('window');
let fromBounds = {
  x: width - 56,
  y: 20,
  width: 44,
  height: 44,
};
Menu.show(fromBounds, items, 'end');
```

**Comment by PeterLocas** [comment]
多谢大神🙏

**Comment by rilyu** [comment]
客气了，刚好今天有空

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32877815-eb7c8a14-ca68-11e7-9f9e-b5fb2dfbe103.png)
你看看这个是啥情况

**Comment by rilyu** [comment]
fromBounds 不要加大括号了。。。
Menu.show(fromBounds, items, 'end');

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32878038-f587b898-ca69-11e7-9293-49a676b8e489.png)
嗯去掉了，不知道哪里的问题

**Comment by rilyu** [comment]
Menu.show(fromBounds, items, {align: 'end'});

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/32878606-518f2f34-ca6c-11e7-9d9e-679b4fb6354d.png)
可以了大神，menuItemIconColor必须设置吗，不能呢按原来icon的颜色吗

**Comment by rilyu** [comment]
menuItemIconColor: undefined,

这样应该就是图标原色

**Comment by PeterLocas** [comment]
多谢 
![image](https://user-images.githubusercontent.com/5467858/32879621-54855b74-ca70-11e7-90a0-371b16d6f67e.png)


大神点击这里会卡一秒中，不知为何
![image](https://user-images.githubusercontent.com/5467858/32879627-60fc6870-ca70-11e7-9d35-a17fb3501c53.png)

**Comment by danna88** [comment]
@PeterLocas 请问你用这个menu的时候，那个菜单的箭头showArrow为true，会有箭头出现吗？ 出现的位置对吗？
