### ISSUE TITLE
大神，你这个导航支持back到指定页面吗

### ISSUE THREAD

**Issue by PeterLocas** [rilyu/teaset#89]
NavigationPage是否可以backto some page

**Comment by rilyu** [comment]
可以
this.navigator.popN(2) 返回两层
this.navigator.popToTop() 返回到顶层
this.navigator.popToRoute(route) 返回到指定路由，使用这个方法你需要在this.navigator.push时自行维护路由表

**Comment by PeterLocas** [comment]
@rilyu NavigationPage 高度能调整吗
![image](https://user-images.githubusercontent.com/5467858/32927813-70f8332c-cb14-11e7-8ff4-0ae48ddfafc1.png)
android的这个有点搞

**Comment by rilyu** [comment]
这是标准的高度的，在 iOS 包括状态栏 64 ，Android 不包括状态栏 44 ，在设计时没考虑调整高度，操作起来会很麻烦
