### ISSUE TITLE
SegmentedView在和flatList联合使用的时候有bug，下拉刷新时还可以左右滑动

### ISSUE THREAD

**Issue by dudu90** [rilyu/teaset#91]

**Comment by rilyu** [comment]
type='carousel' 时是可以左右滑动的，使用 projector 则不能滑动

**Comment by dudu90** [comment]
@rilyu 那怎么能和FlatList联系到一起呢，我看没有相应的回调

**Comment by rilyu** [comment]
不太明白你说的联系是什么概念，请描述得更为详细一些

**Comment by dudu90** [comment]
@rilyu SegmentedView中嵌套FlatList，FlatList支持下拉刷新，在下拉的时候，SegmentedView依然可以左右滑动，这样就造成了FlatList下拉出现问题，

**Comment by rilyu** [comment]
滑动切换页面导致 FlatList 显示不正确，这是 FlatList 的问题，你需要维护 FlatList 的刷新状态，然后在 SegmentedView.onChange 检查 FlatList 的状态并作相应的处理，比如 forceUpdate 刷新组件显示，具体要尝试一下
或者，你检测到 FlatList 在下拉刷新时禁止 SegmentedView 组件的 refs['carousel'] 滚动，需要先获得 SegmentedView 的 ref 对象

**Comment by dudu90** [comment]
@rilyu 关键是FlatList并没有提供相应的回调方法，

**Comment by rilyu** [comment]
监听 onRefresh 并配合 refreshing 属性管理刷新状态

**Comment by dudu90** [comment]
@rilyu 这个可以做到，但是现在的问题是，下拉的时候有问题，下载在onRefresh回调之前

**Comment by dudu90** [comment]
@rilyu 我的思路是监控FlatList的手势然后做相应的处理，但是还有搞好。
