### ISSUE TITLE
大神，请问什么时候可以适配iPhone X这个奇葩界面？

### ISSUE THREAD

**Issue by decano-net** [rilyu/teaset#92]
我已经关注了好久，没能等到更新，只能厚脸皮问您了，拜托咯！

**Comment by rilyu** [comment]
买不到 iPhoneX ，需要体验过才知道怎么适配更合适，在模拟器上看至少是能工作的，只是不太好看

**Comment by decano-net** [comment]
真机也是能工作，上下都是黑的多不好看那~~
拜托大神有空在虚机上捣腾一下或者给个思路可以吗，有RN已经实现的例子不？

**Comment by Alan201601** [comment]
我昨天也在iphone X上面也遇到了这个问题，引入了轮播图，导致整个界面都是黑色的

**Comment by Alan201601** [comment]
最后我是在最外层的view上面添加了style={{backgroundColor:'#fff'}}
