### ISSUE TITLE
我用TabView之后，我想从其中一个页面跳到一个没有底下tabbar的页面怎么办

### ISSUE THREAD

**Issue by zust-hh** [rilyu/teaset#93]
如题，恳请大牛您解答，拜谢

**Comment by rilyu** [comment]
参考例子：https://github.com/rilyu/teaset/blob/master/example/views/TabViewExample.js
TabView.Sheet.type 设为 button，然后在 onPress 调用导航器的转场功能就行了
```javascript
      <TabView.Sheet
        type='button'
        title='Custom'
        icon={bigIcon}
        iconContainerStyle={{justifyContent: 'flex-end'}}
        onPress={() => alert('Custom button press')}
        />
```

**Comment by zust-hh** [comment]
![image](https://user-images.githubusercontent.com/26922852/33068760-3d320446-ceed-11e7-8ccc-b068cbf7f6ea.png)
您好，我的意思是这样，点击其中一个页面中的某个按钮，跳转到其他一个没有tabbar的页面
还有导航器是指TeaNavigator吗？我一直没弄明白这个在onpress里怎么用

**Comment by rilyu** [comment]
有很多导航器，建议你找相关文档了解一下，example 使用了 TeaNavigator，你也可以参考一下

**Comment by zust-hh** [comment]
我知道有很多导航器，但是我在按钮按钮加onpress导航之后，页面默认还是在tabview中，底下还是有tabbar的，我就想知道怎么能跳到一个没有tabbar的页面。
